### ISSUE TITLE
Operator: MetricsInstance should use password file

### ISSUE THREAD

**Issue by hjet** [grafana/agent#1061]
@rfratto to add more context

**Comment by rfratto** [comment]
basic_auth is hard coded in the operator to use password instead of password_file: https://github.com/grafana/agent/blob/7b4a36e366a6f7958ec3d9c93e9d084508836e61/pkg/operator/config/templates/component/metrics/remote_write.libsonnet#L33

While the agent config is also a secret, not using the file form when its available means that the agent is forced to wait a little longer before picking up secret changes. We should use _file forms whenever they're available.
