### ISSUE TITLE
Metrics: stop writing duplicate exemplars

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1282]
@bboreham noticed that 95% of exemplars being sent by Grafana Agent are duplicates, each costing some amount of disk I/O on the receiving side. 

Prometheus supports a [circular buffer](https://github.com/prometheus/prometheus/blob/4855a0c067e25df969debbe880448164116f625e/tsdb/exemplar.go#L118) for storing exemplars in memory. This can be utilized during validation of an exmplar to ignore existing exemplars, preventing duplicate writes. 

cc @mapno

**Comment by tpaschalis** [comment]
I peeked at the CircularExemplarStorage implementation.

Some notes:
- The size of the buffer is configurable. The size in DefaultExemplarsConfig is 100k elements, but I think I'm not sure it's enabled by default.
- It's used as the only concrete implementation of the `ExemplarStorage` interface
- It implements the Select method to filter exemplars based on label matchers and IterateExemplars to flush them when creating a chunk snapshot.
- Some exemplar-related metrics are registered on startup, and like other components, it supports applying config, resizing and reloading.

From what I gather, the two methods we need are `AddExemplar()` and its `validateExemplar()` helper, which attempt to add items to the in-memory storage and return an error if a duplicate already exists. I think that ValidateExemplar is used to validate items already appended to the storage, but I'll check again.

I've started on a small draft, bringing in some part of the code to test and benchmark how useful

**Comment by bboreham** [comment]
Agent would only need the last exemplar for each series, not the full circular buffer.
Having a fixed cap is counterproductive here, I think.

**Comment by rfratto** [comment]
> Agent would only need the last exemplar for each series, not the full circular buffer.
> Having a fixed cap is counterproductive here, I think.

That's a good point. We can probably just keep the exemplar into the `memSeries` struct instead of using the circular buffer. 

(Though it does raise the question of what Prometheus needs the circular buffer for)

**Comment by tpaschalis** [comment]
> (Though it does raise the question of what Prometheus needs the circular buffer for)

I glanced through the Prometheus implementation [1]  and seems like the choice of the circular buffer was so that they could bound the overall memory usage by a single config parameter without having  a specific limit of exemplars per series, other than that global limit. As they wouldn't store exemplars in disk, the circular buffer was used as a best-effort minimal storage and deduplication was not the primary goal.

If we're okay with only comparing with the last exemplar for each series, I can look into storing it into `memSeries`. The extra overhead would be incurred _per active series_ and the original design estimates the average case at 95 bytes per exemplar, while the worst case scenario at 328 bytes per exemplar.

I'm not sure whether this unboundedness is cause for concern, but the memory usage wouldn't be dramatic (100k series with exemplars would lead to 9.5MB (avg) to 38.2MB (max) increase).

[1] prometheus/prometheus#6635, prometheus/prometheus#8296, [design doc](https://docs.google.com/document/d/1ymZlc9yuTj8GvZyKz1r3KDRrhaOjZ1W1qZVW_5Gj7gA/edit#)

**Comment by bboreham** [comment]
Making `memSeries` bigger will penalise every metric - typically only a small subset have exemplars.

**Comment by rfratto** [comment]
Yep, also a good point. `memSeries` is already 56 bytes, and adding a pointer to an exemplar would make all series require 14% more memory. 

A separate striped map in `stripeSeries` to get the latest exemplar for some ref ID would be cheaper. I'm just talking off the top of my head though, I'll leave it to @tpaschalis to figure out what has the most acceptable set of tradeoffs.
