### ISSUE TITLE
Grafana agent instance label and agent_hostname

### ISSUE THREAD

**Issue by ssesha** [grafana/agent#134]
I have cortex setup and was configuring grafana cloud agent to scrape and forward metrics according to [this](https://grafana.com/blog/2020/07/02/getting-started-with-the-grafana-cloud-agent-a-remote_write-focused-prometheus-agent/). So, I have multilple machines and cloud agent is running in each of them. I noticed that, for the node_exporter integration, a new label agent_hostname is added, which has the actual hostname, apart from the instance label, which has value localhost:xxxx.
I was also trying to scrape envoy metrics and added a scrape config for the same - providing a static config to localhost. In the envoy scraped metrics i do not see any agent_hostname label added and the instance value is localhost for metrics from all the different machines. SInce, the instance value is the same, the series are not differentiated and this causes issues.

The solution i understand is to use `metric_relabel_configs` and change the instance value to the actual hostname. My question is why was this approach not taken for the node_exporter integration and why add another label `agent_hostname`. What's the right way to accomplish this?

**Comment by rfratto** [comment]
Hi! Having the integrations write the hostname to the `instance` label instead of localhost makes a lot more sense than the separate `agent_hostname` label, but it's harder than it sounds to implement, so it'd take some amount of care to have it be done transparently to the users. 

The separate `agent_hostname` integration label breaks a lot of existing dashboards that depend on `instance` being the unique label, so I'm interested in changing the behavior here relatively soon (cc @eamonryan). For your specific use case, it'd be useful if you could tell the "normal" scrape configs to replace the instance label with the machine hostname as well. 

For now, `metric_relabel_configs` is the way to do it until we have something better in place.

**Comment by ssesha** [comment]
Thanks so much. This is the clarification I wanted!
