### ISSUE TITLE
Proposal: Extend API to support logs and traces 

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1404]
The Grafana Agent API currently has two endpoints to examine the state of metrics:

* [`/agent/api/v1/instances`](https://grafana.com/docs/agent/latest/api/#list-current-running-instances) returns the list of metrics instances 
* [`/agent/api/v1/targets`](https://grafana.com/docs/agent/latest/api/#list-current-scrape-targets) returns the list of Prometheus SD targets across all instances. 

I propose: 

* Adding similar endpoints for logs and traces 
* Aliasing the current endpoints to clarify it's metrics-specific 

As a result, the following endpoints would be available: 

* `/agent/api/v1/metrics/instances` (alias of `/agent/api/v1/instances`)
* `/agent/api/v1/metrics/targets` (alias of `/agent/api/v1/targets`) 
* `/agent/api/v1/logs/instances`
* `/agent/api/v1/logs/targets`
* `/agent/api/v1/traces/instances`
* `/agent/api/v1/traces/targets`

**Comment by marctc** [comment]
After a bit of discussion with @mapno we came up with two approaches that we could do in order to get the targets of an instance for the traces subsystem. The idea is to propagate the info collected for [prom_sd_processor](https://github.com/grafana/agent/blob/main/pkg/traces/promsdprocessor/prom_sd_processor.go#L27) to the instances as it includes information of the targets pushing traces.

- Store the [`promServiceDiscoProcessor`](https://github.com/grafana/agent/blob/main/pkg/traces/promsdprocessor/prom_sd_processor.go#L27) instance in a struct and returning it when the `NewFactory`(https://github.com/grafana/agent/blob/main/pkg/traces/promsdprocessor/factory.go#L41) is invoked. This would allow to run something `instance.GetFactory` to retrieve the tagets info.
- Create an extra pipeline with an exporter that holds the information of the targets. This would allow to run something like `instance.GetExporter` to retrieve the targets info.

(@mapno please clarify here if i'm missing something here)

IMHO both implementations seem hacky and rather complex. I'd suggest to close this issue and open another one in the future if there's a need to have an endpoint to fetch targets for traces.

**Comment by rfratto** [comment]
I'm fine with that 👍
