### ISSUE TITLE
Add opt in feature telemetry

### ISSUE THREAD

**Issue by mattdurham** [grafana/agent#1488]
Add telemetry on major feature flags being used, this will help Agent team determine if a feature is getting enough traction to graduate from experimental/beta and what users are finding helpful/useful.

Ideals:
- Opt in only, likely via a flag
- No identifiable information, ie no ips, usernames, ect
- No sensitive information was sent, ie record that remote configuration is being used but not the URL
- Configurable endpoint and easily view what is sent (add to logs?)

The initial dataset is the feature flags used, and if the scraping service is being used.

**Comment by rfratto** [comment]
Agree that this would be useful for us to find out who is using what so we can make more informed development decisions, and 100% agree that it's very important for this to be opt-in. (Though I'm personally OK with it being set in the YAML so you can opt-out dynamically without having to restart) 

Loki recently added usage reports in to its server too: grafana/loki#5361 
Current Loki code is here: https://github.com/grafana/loki/tree/main/pkg/usagestats

**Comment by rfratto** [comment]
I asked around how this works for Loki and Grafana and was told that:

* Grafana sends the usage report every 24 hours when enabled, and Loki sends it every 4 hours when enabled. 
* Both Loki and Grafana store a random UUID fingerprint for each instance so that usage stats from the same process can be correlated but still be anonymous and non-identifiable

**Comment by marctc** [comment]
> Ideals:
> 
>     * Opt in only, likely via a flag
> 

We decided to change it to opt out. The reason is temporarly documented [here](https://github.com/grafana/agent/pull/1661).
