### ISSUE TITLE
Code sign Windows binaries

### ISSUE THREAD

**Issue by splitt3r** [grafana/agent#1557]
Same as https://github.com/grafana/agent/issues/652 but for the Windows installer.

**Comment by rfratto** [comment]
Hi, this is something that we've discussed a few times internally, but at the moment we don't anticipate doing this; it's a significant undertaking to code sign binaries, and there doesn't seem to be a precedent of other OSS projects doing this. 

I'm going to close this since we have no plans on doing it, but we're always open to changing our minds in the future.
