### ISSUE TITLE
Include Loki configuration in Tanka configs

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#156]
The Tanka configs should be updated to _optionally_ add in Loki configs. The [upstream Promtail Tanka](https://github.com/grafana/loki/tree/master/production/ksonnet/promtail) should be matched identically here. It's probably more appropriate to make a hard copy rather than import it.

Additionally, since the Loki configs will be optional, the Prometheus configs should also be made optional. There should be a configuration option for suffixing the name of the Agent deployment so a Prometheus-only deployment and a Loki-only deployment can coexist in the same namespace. 

The Kubernetes manifest should only contain Prometheus configs for now until we figure out how to create an all-in-one installation script. Alternatively, a second installation script and manifest can be created specifically for logs.

**Comment by rfratto** [comment]
There's an opportunity for some code cleanup here and removing some kludge. The default deployments ship with `privileged: true`, which I'm pretty sure isn't necessary at all. We'll need to find out if it's still necessary for Promtail (where it originally came from), but we should definitely take it out if Promtail isn't being utilized.

**Comment by slim-bean** [comment]
The answer here is gonna be complicated because I think it's "it depends". Not all operating systems allow reading from /var/log as non root and more so I haven't seen any allow reading from /var/lib/docker as non root. Additionally we put the positions file in /var/log which definitely needs to be root to create.

Is it possible to run promtail as non root? Yes but it's not going to be easy or very portable I fear between operating systems

**Comment by rfratto** [comment]
Thanks! I'll make it configurable and enable it by default when the user is deploying the Agent for log collection.
