### ISSUE TITLE
docs/user/operator/custom-resource-quickstart.md: wrong `up{job=…}` metrics

### ISSUE THREAD

**Issue by flokli** [grafana/agent#1606]
A bunch of Grafana Kubernetes Dashboards (like the default ones produced by `kubernetes-monitoring/mixins` - rendered at https://github.com/monitoring-mixins/website/tree/master/assets/kubernetes/dashboards, use the following query to construct the `$cluster` dashboard variable:

`label_values(up{job="cadvisor"}, cluster)`

Likewise, there's other queries using `job="kubelet"`.

This means, it'd be convenient if the quickstart in `docs/user/operator/custom-resource-quickstart.md` would provide the same `job` labels that are expected there, to provide a nice out of the box experience.

However, things are a bit convoluted.

The `up` metric seems to have the `job=kubelet` label (this seems to come from the job name in the rendered scraping config), as the `metricRelabelings` line only seems to apply to individual metrics, not the `up` job describing the scrape job.

```
    - action: replace
      targetLabel: job
      replacement: integrations/kubernetes/cadvisor
```

Also, as can be seen there, this should be set to `cadvisor`, not `integrations/kubernetes/cadvisor`.

**Comment by flokli** [comment]
It seems `servicemonitors.monitoring.coreos.com.spec.jobLabel` might be the right attribute to set, to replace all `job` labels in the returned metrics properly. 

However, the description 

> The label to use to retrieve the job name from.

… doesn't really elaborate on which resource needs to be labelled to be able to define a custom job name.

**Comment by flokli** [comment]
not stale

**Comment by hjet** [comment]
hey there @flokli thanks for surfacing this!

1. so this was originally written so that users could follow the quickstart, and have it work "out of the box" with the grafana cloud kubernetes integration (as a drop-in replacement for deploying agent manually using those generated configs & manifests). the integration uses `job=integrations/kubernetes/*` labels, so those are the one we provide in that guide.

we probably should add a note instructing users on how to change this (for example to get this working with different selectors or OSS mixin, etc. "out of the box")

2. great catch, yea it seems like `servicemonitors.monitoring.coreos.com.spec.jobLabel` is [the label to set](https://github.com/grafana/agent/blob/3bdf590192372b1de5741f3dd8248d1f5008cd7d/pkg/operator/config/templates/component/metrics/service_monitor.libsonnet#L203) - this will default to using the service's name if this isn't provided or if the corresponding label name provided as the `jobLabel` is not set on the service. since the service is created by operator (from what i recall) and its name is `kubelet`, i think all the endpoints created will have a `job=kubelet` label set for the `up` metric (and not sure how this interacts with the relabel configs....).

**Comment by hjet** [comment]
based on the ordering, i think using a `relabelings` instead of `metricRelabelings` will solve this. i think it'll override the default `kubelet` value

**Comment by hjet** [comment]
removing bug label for now, will be able to test shortly

**Comment by Wouter0100** [comment]
@hjet I can very it works.

**Comment by hjet** [comment]
> @hjet I can verify it works.

awesome, thanks for verifying! this got away from me - have had a busy couple of weeks. will get to this soon but in the meantime anyone should feel free to put up a PR [here](https://github.com/grafana/agent/blob/main/docs/user/operator/custom-resource-quickstart.md)

**Comment by flokli** [comment]
I took a stab at this in https://github.com/grafana/agent/pull/1810, PTAL.

**Comment by flokli** [comment]
Not stale, waiting for https://github.com/grafana/agent/pull/1810 to be merged.

**Comment by flokli** [comment]
Not stale.
