### ISSUE TITLE
0.24.2 tarball fails Homebrew checksum

### ISSUE THREAD

**Issue by gromgit** [grafana/agent#1699]
Hi! I help out with the Homebrew project, and I just noticed that the current 0.24.2 source tarball does not match the one recorded in our `grafana-agent` formula. Specifically, we record SHA256 checksums of source tarballs every time we build a new version of each formula, and as at **2022-05-02 22:15:37 UTC**, your source tarball was checksummed as `c1657743ed2c3dd7dff1cc3a9777c5b7e950d163d6092cc5159b2198f555fff9`. However, the current tarball checksums as `b7d96405ce9b58a371e9c5fc19bf3f13dd967a2c192bf3f7ae4f3f76ee581077`.

Was the source tarball changed since the abovementioned timestamp? If so, may I know what was changed?

Thanks much!

**Comment by tpaschalis** [comment]
Hey Adrian, thanks for bringing this to our attention! You're right, there's this difference which I think was a mis-sequencing of steps during our last patch release.

/cc @captncraig @rlankfo. On the [release-v0.24 branch](https://github.com/grafana/agent/tree/release-v0.24) I can see the `bump-formula-pr` job failing with the following message

```
Error: These pull requests may be duplicates:
grafana-agent 0.24.2 https://github.com/Homebrew/homebrew-core/pull/100646
Duplicate PRs should not be opened. Use --force to override this error.
```

IIRC that during that patch, we deleted and re-created the tag for a last-minute CHANGELOG fix, right? I think that the CI pipeline it had enough time to create the two automated PRs ([1](https://github.com/Homebrew/homebrew-core/pull/100646), [2](https://github.com/grafana/homebrew-grafana/pull/29)) the first time around with the erroneous `c1657..` checksum, which we then also updated with the bottle hashes.

When the new tag was re-created it with the current `b7d96..` checksum, the job it detected a duplicate PR and didn't proceed, but we didn't get wind of it, and merged the first PRs instead. Replaying the `bump-formula-pr` job also doesn't help, since the PRs labelled `v0.24.2` are already merged.

Should we re-run the automations with the --override flag so that the new PRs get created with the correct checksums? Is there a better solution on the homebrew ecosystem?

**Comment by gromgit** [comment]
If there were changes that absolutely need to be distributed to existing users, then a PR containing:
* the corrected `sha256` field and
* a `brew bump-revision` run
would be needed. If not, then a PR with only the `sha256` correction should be sufficient.

Given the basic nature of the changes, a manually-generated PR would probably be a better choice.

**Comment by tpaschalis** [comment]
We can go with just correcting the checksum. Feel free to open the PR and tag one of us as a reviewer for an approval. Again, thanks for letting us know!

**Comment by gromgit** [comment]
OK, the checksum has been fixed, and confirmed with a local Homebrew build from source, so I'm closing this issue.
