### ISSUE TITLE
Grafana Agent - UI for Viewing Targets/Service Discovery/Config

### ISSUE THREAD

**Issue by rjpnps** [grafana/agent#1764]
Troubleshooting scrape configs in Grafana Agent is **hard** - the only debug tooling available is through the agent's logs (which is not the most effective approach for debugging scrape config).

Prometheus has a web UI composed of Targets, Service Discovery, and Configuration for this:
![image](https://user-images.githubusercontent.com/85288030/171442048-22ec54f2-f3f8-4d44-a345-fff343a39bf4.png)

Could we leverage this feature into the agent?

**Comment by rfratto** [comment]
Hey there! I've always been a fan of this idea, but we haven't had time to devote to it (especially since we couldn't _just_ use the Prometheus UI given how we embed the Promtail and OpenTelemetry Collector, too). 

Long term, I suspect we might end up with a Grafana Plugin that utilizes the API endpoints we've written to build a UI. It'd prevent ballooning the size of the binary any more than it already is and would probably be easier for dealing with a wider of agents.

Still though, a Grafana plugin or a UI in general isn't something we have prioritized at the moment, but we'd love to help contributors bootstrap one if anyone is interested.

**Comment by fgouteroux** [comment]
I agree about the hardness of troubleshooting scrape configs in Grafana Agent. Using the [agent api targets](https://grafana.com/docs/agent/latest/api/#list-current-scrape-targets-of-metrics-subsystem) is useful to understand what is going on. ```curl https://$HOSTNAME:9292/agent/api/v1/metrics/targets | jq .
{
  "status": "success",
  "data": [
    {
      "instance": "30bbfbf2499661fbad7391b65040945f",
      "target_group": "hello-world-app",
      "endpoint": "http://localhost:8080/metrics",
      "state": "down",
      "labels": {
        "instance": "localhost:8080",
        "job": "hello-world-app"
      },
      "discovered_labels": {
        "__address__": "localhost:8080",
        "__metrics_path__": "/metrics",
        "__scheme__": "http",
        "__scrape_interval__": "30s",
        "__scrape_timeout__": "10s",
        "job": "hello-world-app"
      },
      "last_scrape": "2022-06-07T09:12:36.547144881Z",
      "scrape_duration_ms": 0,
      "scrape_error": "Get \"http://localhost:8080/metrics\": dial tcp 127.0.0.1:8080: connect: connection refused"
    },```
