### ISSUE TITLE
Release candidates may cause new versioned docs to be created prematurely

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#1782]
From what I can tell of our [publish_docs action](https://github.com/grafana/agent/blob/main/.github/workflows/publish.yml) and the [docs-target action implementation](https://github.com/grafana/grafana-github-actions/tree/main/docs-target), any commit to one of our `release-*` branches will cause versioned docs to be created. 

If my understanding is correct, this means if we create a new release candidate in a `release-*` branch, we'll prematurely create versioned docs for it which will be set to the latest version. 

It seems like the preferred behavior is that we only create new versioned docs after the initial tag is made, though maybe the behavior I described is fine as-is. 

cc @jdbaldry @tpaschalis

**Comment by rfratto** [comment]
If the behavior is going to be changed, a fix isn't pressing and just needs to be done by v0.26.0 (~4-6 weeks from now).

**Comment by tpaschalis** [comment]
Yeah, @jdbaldry has anticipated and has a solution for this problem.

The workflow used by Mimir only publishes the versioned docs [if there is a matching release tag](https://github.com/grafana/mimir/blob/a76e2966407b756ea783ccbbf732a9ba49c1bbca/.github/workflows/publish-technical-documentation-release.yml#L40-L46).

I was planning to bring this functionality over to the Agent as well for the next release, but wanted to improve our current way of publishing docs sooner rather than later.

In any case, good catch, and let's leave this Issue open for tracking the solution to this problem.

**Comment by tpaschalis** [comment]
Reopening, as it's still not fixed. I'm going to assign myself so I don't lose track of it this time.
