### ISSUE TITLE
Improve Github Integration

### ISSUE THREAD

**Issue by proffalken** [grafana/agent#1845]
I'd like to improve the Gihub Integration so we can get the following metrics:

1. Issue state (at the moment, it only returns "open" issues.  We'd like to track open vs closed vs reopened over time)
2. Contributors, ideally with the number of PR's they've approved on the repo etc
3. Enhanced PR data such as checks passed, approvals required vs approvals granted, and merged vs awaiting merge

I'm struggling to find the code where this would happen, can anyone enlighten me?

**Comment by rfratto** [comment]
Hi! We already had a chat on the public Slack, but I'll rewrite my answer here for anyone else who might be curious.

I definitely agree these things would be useful. Unfortunately, there's not much code in this repository for the exporter itself. Our code is in [pkg/integrations/github_exporter](https://github.com/grafana/agent/blob/2ead6edb2f55144ba8cad57e89ddf1c625c8bc1f/pkg/integrations/github_exporter/github_exporter.go), which wraps around the open source [infinityworks/github-exporter](https://github.com/infinityworks/github-exporter) exporter. 

We tend to opt for existing exporters from the community so that:

* We don't reinvent the wheel for code that already exists 
* We can add more integrations into the agent quickly 
* We help give existing exporters in the community get more attention 

Fixes and new features would have to be made upstream, which we could then re-import downstream. 

In this case, it looks like there hasn't been much activity in this specific upstream exporter. If the repo has become stale, we'll want to discuss whether it makes sense to do nothing (e.g., if it's considered feature-complete), fork it, find another existing exporter, or to write a new exporter for GitHub metrics.

**Comment by proffalken** [comment]
Finally got around to logging https://github.com/infinityworks/github-exporter/issues/85 to find out what the state of the exporter is and see where we go from here.

**Comment by proffalken** [comment]
Given there's been no reply to my issue raised on the other repo, then I think we need to assume that the other project is dead.

Probably need to have a think about where we go from here, as being able to timestamp from git PR's is a really important part of our end-to-end observability

**Comment by marctc** [comment]
@proffalken if the project is not really maintained (but still relevant) I think it could be transferred [here](https://github.com/prometheus-community) which there are already _non-official_ exporters. Although is just my opinion: not sure if any of both orgs would agree on doing this transfer of ownership.

**Comment by proffalken** [comment]
@marctc good idea, I'll log a ticket over there and see what they think.

**Comment by proffalken** [comment]
Need to spend some time on the upstream to port it over to the prom community plugins repo

**Comment by marctc** [comment]
Looks like github-exporter has been moved its own organization: https://github.com/githubexporter/github-exporter.

**Comment by proffalken** [comment]
@rfratto  - does the information from @marctc mean that we'll automatically see updates from the new maintainers, or is there work to do in order to switch it over?

**Comment by marctc** [comment]
Hey @proffalken, I tried to switch to the org/repo but I got some errors. This [PR](https://github.com/githubexporter/github-exporter/pull/100) upstream should fix the issue.
