### ISSUE TITLE
Agent's `/metrics` endpoint does not respect `scrape_integration`

### ISSUE THREAD

**Issue by luizberti** [grafana/agent#196]
I currently have the `agent` integration disabled, but `agent_*` metrics still appear in `/metrics`. The `/metrics` endpoint should only show things that are being scraped from targets, otherwise `remote_write` will diverge from what `/metrics` show. Those `agent_*` metrics should only appear there if the `agent` integration is enabled and `scrape_integration` is set to `true`.

A similar thing happens to the `node_exporter` integration, but in reverse: if the `node_exporter` integration is enabled and `scrape_integration` is set to `true`, I would expect to see its metrics on `/metrics` but instead they still only appear under `/integrations/node_exporter/metrics`. The expected behavior would be that those metrics show on `/metrics` with all of the label information explicitly attached, so that a Prometheus instance scraping `/metrics` with `honor_labels: true` would faithfully mirror what gets received at the `remote_write` endpoint.

**Comment by rfratto** [comment]
I think there's a miscommunication here about the intended purpose of `/metrics`. The `/metrics` endpoint is an alias for `/integrations/node_exporter/metrics`, and are intended to expose the metrics for monitoring the Agent itself.

If `scrape_integration` is true, the Agent will collect metrics from `/integrations/*/metrics` and ship those off to the associated `prometheus_remote_write` config section. You shouldn't have any manual scrape_configs for these endpoints if the Agent is collecting them itself, otherwise you will get some writes rejected from the remote_write system. If it's `false`, then you _have_ to scrape the endpoints yourself by defining multiple scrape jobs with a different `metrics_path` setting per integration. 

We currently don't have any plans for the root `/metrics` endpoint to consolidate metrics from all the integrations, but I'd like to hear your use case about why the other approach wouldn't work for you. 

(Enabling `agent` integration with `scrape_integration: false` isn't very useful, since those metrics are already exposed via `/metrics`.)

**Comment by luizberti** [comment]
I see your point. What I wanted is for the agent to expose a `/federate` endpoint, like the official Prometheus does, my use case is that I want to have in-cluster monitoring, on top of what's forwarded to Grafana Cloud.

The reason for this is that there is a mismatch between what is useful for me _right now_ if I'm debugging something, and what is useful for me _to forward and retain off-cluster_, so we wanna have tons of metrics in-cluster but with short retention, and forward a heavily filtered version of that to Grafana Cloud so we have off-cluster alerting and long-term retention but in a cost-effective way, rather than blowing up our monitoring budget.

Right now, there doesn't seem to be a decent way to filter the metrics that are being remote_written (not agent's fault though, upstream Prometheus doesn't have anything either). The way we fixed this was by departing from an `agent` based monitoring system, to using them exclusively as a 2-in-1 promtail+node_exporter daemon, being scraped by two redundant in-cluster Proms, then in the same Pod for each of those Proms we have the `agent` again but as a sidecar, scraping the `/federate` endpoint, applying `metrics_relabel` filtering, and remote_writing to Grafana Cloud's Cortex (which handles de-duping the redundant data from the Proms).

It's kinda rube-goldberg-machinesque but it works alright and stresses the API Server way less than having the agent running service discovery on each node. A more straight-forward mechanism for accomplishing this would be much appreciated however.

**Comment by rfratto** [comment]
I'm open to creating an `/integrations/all/metrics` endpoint that aggregates all metrics across all enabled integrations. We would need to add a label indicating which integration individual metrics came from to prevent any chance from two future integrations clashing with duplicate series/labels. 

Would that work for you? I'm hesitant to name the endpoint `/federate` since the endpoint wouldn't be compatible with the official federation endpoint (i.e., no support for `match[]` in params).

**Comment by luizberti** [comment]
Yeah, that is functionally equivalent to what I was going for. As long as the exposed metrics have all the labels that would be passed onwards with a `remote_write` (or can be configured to include those), so that scraping it with `honor_labels: true` would yield a faithful representation of the data being remote written, that'd be perfect.

Even with our current setup, having an easy way to inspect what's being scraped (such as with `prom2json`), or even simulating Grafana Cloud locally with Prometheus for trying out dashboards and alerts without having to consume our usage quota (since this can easily rack up a thousand dollar bill) would make the Agent much simpler to work with, and lead to less convoluted workarounds.
