### ISSUE TITLE
subsystems can crash "undetected"

### ISSUE THREAD

**Issue by robx** [grafana/agent#207]
It appears that when a subsystem dies (loki logging in particular is a case we ran into), the agent process keeps running happily without restarting the subsystem. It seems this should be dealt with better in some ways, e.g.:

- exit when a subsystem exits, so that OS level process management can restart the agent
- restart the subsystem when it fails

Some explicit agent-level logging when a subsystem fails would also be nice.

(My understanding of this is based on reading around https://github.com/grafana/agent/blob/60e9cbb63c6bb5ca8fa70b9a774ee969f2c65f85/cmd/agent/main.go#L64, https://github.com/grafana/agent/blob/60e9cbb63c6bb5ca8fa70b9a774ee969f2c65f85/pkg/loki/loki.go#L49, https://github.com/grafana/agent/blob/60e9cbb63c6bb5ca8fa70b9a774ee969f2c65f85/vendor/github.com/grafana/loki/pkg/promtail/promtail.go#L38, though I'll have to admit I didn't trace things quite far enough to understand where the loki subsystem's `Run()` is actually called (if at all).)

In the concrete case this is based on, the Loki subsystem stopped with this error:

```
level=error ts=... caller=tailer.go:108 component=loki component=tailer msg="error getting tail position and/or size, stopping tailer"
 path=.../logs/some.service.stderr.0 error="invalid argument"
```

and the agent kept on running happily, logging about the prometheus integration.

**Comment by rfratto** [comment]
This is easiest to do with the Prometheus subsystem, but this will be fairly tricky with everything else. It seems like both the Tempo subsystems and the Loki subsystems both start goroutines for the main logic and don't have any way to signal that the run loop exited on its own. 

Though I agree this is a problem that needs to be fixed, I don't think this is what is happening based on the log line you showed. That just looks like an individual file tailer for a specific target stopped rather than all of Promtail. @cyriltovena was saying this offline in our Slack. 

Hopefully it's not too difficult to invert the control here and move control over launched goroutines to the caller. Looping in more people to get their thoughts on this: 

Tracing: @joe-elliott 
Loki: @grafana/loki-team (sorry for tagging everyone, I don't want to play favorites 😛)

**Comment by cyriltovena** [comment]
This is something I'm pretty sure everyone is open to have in Promtail.
