### ISSUE TITLE
UI: Objects no longer indented and aligned

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2689]
As of either #2683 or #2642, aligning of multiline values stopped working:

Before:

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/630212/211123634-0819357b-c95b-4569-a625-c6b987822a2a.png">

After:

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/630212/211123647-0e6c4ebe-02fc-449d-91e5-19435a2f5732.png">

Is this because extra whitespace is getting removed?

cc @xiyu95

**Comment by xiyu95** [comment]
Very likely. In order to fix the long string, since it's a single word string, I had to apply a normal white space to the css. And code block seems to be included as well. I will take a look at it!

**Comment by xiyu95** [comment]
@rfratto I think I will refactor the code in an approach to separate a normal pair of `name:value` with object type `name:value` view. That is, for any value that is an object type, instead of partitioning the space in, I will create a new table/grid layout for them to have 3 columns with the later 2 columns serving the `value.key` and the `value.value`. This way, it will be simpler without needing to calculate the length and space.

Before doing so, I am just wondering if you ever seen libraries like `React-json-view`. A short description to the library is that it will take any object type and directly render it as the object format, screenshot below. Pros (for `React-json-view` specifically) would be easy to implement, and little to none custom styles needed. Cons will be in our case, `=` will changed into `:` as it is a json format, and space between lines will be slightly bigger causing the block to be long.

![Screen Shot 2023-01-10 at 10 05 41 AM](https://user-images.githubusercontent.com/112968312/211628380-de51ff96-60e7-4efb-8c55-80327f7cda40.png)

If this kind of library l will look around for more similar ones, otherwise, I will use the approach (table/grid layout) above to accomplish the task.

**Comment by rfratto** [comment]
The original intent was that the value shows up as it would in the config file (i.e., River). Can I see a mockup of what you're proposing?

**Comment by xiyu95** [comment]
> the Flow config file (i.e., River)

Did you mean the `.river` files from the repo? In that case I think it would be better with the origin `table` approach, but here is a quick screenshot to it using one of the agent components (There is an extra pair of `[` and `]` coming from the `array` type case), but this screenshot should be enough to show a simple demo of what it will look like by applying `React-Json-View`
![Screen Shot 2023-01-10 at 12 06 26 PM](https://user-images.githubusercontent.com/112968312/211651330-5dc36bf0-7395-459f-819d-735e79ea03d6.png)

**Comment by rfratto** [comment]
> Did you mean the .river files from the repo? 

Yes, sorry, that's what I meant. 

wdyt about changing it to be a view like this @tpaschalis @mattdurham? I'm on the fence about moving away from the River representation.

**Comment by mattdurham** [comment]
@xiyu95  Do those down arrow markers allow you to expand and contract the sub fields?

**Comment by xiyu95** [comment]
> @xiyu95 Do those down arrow markers allow you to expand and contract the sub fields?

Yea, it can collapse or expand. We can set it to collapse at initial render too so it doesn't open up like this when users first visit the page. In our case (second screenshot) they are only `string` values, so might not be as visible, but for any `object` or `array` type it will be able to open/close (such like the first screenshot)

**Comment by mattdurham** [comment]
Getting that for free is a big win, though the copy paste ability drops. If this page is meant more for debugging and seeing the health then I am for it.

**Comment by xiyu95** [comment]
I think the library comes with a property to turn on/off the clipboard, which enable/disable the copy/paste function, if you mean to remove that.

**Comment by mattdurham** [comment]
Sorry, should have clarified. Copy-pasting is fine, was speaking of the ability to copy a section and paste it into the river config.

**Comment by tpaschalis** [comment]
Chiming in with my 2¢ I personally am not suuper fond of that view.

* The plaintext approach is closer to how a River would feel and how `riverfmt` would format it
* The user can no longer copy-paste back into River files (eg. copying a file target to a test component) due to the `:` and missing commas
* If we've gotten to a point where we have 4 or 5 levels of nesting where this would be really useful, then we've already lost the game

**Comment by xiyu95** [comment]
> ability to copy a section and paste it into the river config.

With this said, and what @tpaschalis has mentioned above. I do believe it's good to keep the original ones and fix the formatting like the screenshot below (done in a hacky way, will do in a more proper way once everything is finalized).

If the `react-json-view` lib is something that seems interesting, we could consider adding that in to the page in the future as a secondary viewing option. What do you all think?

![Screen Shot 2023-01-11 at 12 06 24 PM](https://user-images.githubusercontent.com/112968312/211907020-408c8f63-b91b-44c2-8223-cea8017adaaa.png)
