### ISSUE TITLE
Flow: add `constants` identifier

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#2703]
I think it would be immensely useful to have some constants available for use throughout expressions:

* `constants.hostname`: hostname of the machine the Agent is running on 
* `constants.os`: Operating System the agent is running on (e.g., GOOS)
* `constants.arch`: Architecture of the system the agent is running on (e.g., GOARCH)

Maybe more would be useful over time, but these are the initial set that I'd personally like to see. 

These would be especially useful alongside #2638 to use them inside conditional expressions.

**Comment by tpaschalis** [comment]
Yep, I'm up for this. Until I add the proposal around aliases, this is a good starting point to build more flexible configurations.

This also means that `constant` would be a reserved keyword for component Arguments, right? Any other side-effects?

**Comment by rfratto** [comment]
> This also means that constant would be a reserved keyword for component Arguments, right? Any other side-effects?

Right, it effectively becomes an identifier in the stdlib. I don't think there's any other side effects.

**Comment by weakcamel** [comment]
On a related note, I've stumbled across a problem while using `constants.hostname`.

When Grafana Agent is deployed as a Kubernetes application (with the [official Helm chart](https://github.com/grafana/agent/tree/main/operations/helm/charts/grafana-agent)), this constants resolves to the **pod name** and not the actual machine's hostname (node's hostname).

* is that the intended/expected behaviour for a K8s deployment?
* if yes, this means the advice in https://grafana.com/docs/agent/latest/flow/reference/components/discovery.kubernetes/#limit-to-only-pods-on-the-same-node doesn't really work; any suggestions how it should be re-written to actually be effective?

As it is, the suggested `selector` resolves for me to something like

![Screenshot 2023-11-29 at 13 08 27](https://github.com/grafana/agent/assets/2445059/64428490-bfe7-4c2f-a686-45832b7e4f87)

**Comment by clayton-cornell** [comment]
@weakcamel Thanks for your comment. I've opened https://github.com/grafana/agent/pull/5900 to update the example.
