### ISSUE TITLE
[bug] Flow fails to display `loki.source.file` when port-forwarding on kubernetes

### ISSUE THREAD

**Issue by payparain** [grafana/agent#2716]
Using v0.30, when trying to click on a `loki.source.file` block via the UI on the graph, the page receives an empty response and no error/debug logs are emitted by the Agent. The agent _is_ reading log data; I can see it attempting to write it to our remote Loki endpoint, but the visual block for this component isn't viewable. 

<img width="828" alt="Screen Shot 2023-01-11 at 10 20 29 am" src="https://user-images.githubusercontent.com/106503014/211690443-94724311-0bff-48f1-9f15-525570df046b.png">

**Comment by rfratto** [comment]
cc @mattdurham 

I talked to @payparain offline, and there didn't seem to be a panic in the logs. If it's not panicking/failing, maybe it's a timeout problem or a deadlock?

**Comment by rfratto** [comment]
I got the /debug/pprof/goroutine pages offline. There's a deadlock happening here:

`github.com/grafana/agent/pkg/flow/internal/controller.(*ComponentNode).DebugInfo` can't return because the mutex is held by `github.com/grafana/agent/pkg/flow/internal/controller.(*ComponentNode).Evaluate`, which is blocked on being able to stop a target which has shut down:

```
sync.runtime_Semacquire+0x24										/usr/local/go/src/runtime/sema.go:62
sync.(*WaitGroup).Wait+0x51										/usr/local/go/src/sync/waitgroup.go:139
github.com/grafana/agent/component/common/loki.NewEntryMutatorHandler.func2+0x58			/src/agent/component/common/loki/types.go:91
github.com/grafana/agent/component/common/loki.entryHandler.Stop+0x2c					/src/agent/component/common/loki/types.go:67
github.com/grafana/agent/component/loki/source/file.(*tailer).Stop.func1+0x4db				/src/agent/component/loki/source/file/tailer.go:246
sync.(*Once).doSlow+0xc1										/usr/local/go/src/sync/once.go:74
sync.(*Once).Do+0x44											/usr/local/go/src/sync/once.go:65
github.com/grafana/agent/component/loki/source/file.(*tailer).Stop+0x14					/src/agent/component/loki/source/file/tailer.go:227
github.com/grafana/agent/component/loki/source/file.(*Component).Update+0x311				/src/agent/component/loki/source/file/file.go:146
github.com/grafana/agent/pkg/flow/internal/controller.(*ComponentNode).evaluate+0x39c			/src/agent/pkg/flow/internal/controller/component.go:264
github.com/grafana/agent/pkg/flow/internal/controller.(*ComponentNode).Evaluate+0x24			/src/agent/pkg/flow/internal/controller/component.go:215
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).evaluate+0x67				/src/agent/pkg/flow/internal/controller/loader.go:364
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).EvaluateDependencies.func2+0x41e	/src/agent/pkg/flow/internal/controller/loader.go:344
github.com/grafana/agent/pkg/flow/internal/dag.WalkReverse+0x1d1					/src/agent/pkg/flow/internal/dag/walk.go:69
github.com/grafana/agent/pkg/flow/internal/controller.(*Loader).EvaluateDependencies+0x82d		/src/agent/pkg/flow/internal/controller/loader.go:328
github.com/grafana/agent/pkg/flow.(*Flow).run+0x604							/src/agent/pkg/flow/flow.go:192
```

There are also 1470 goroutines stuck trying to send a log line to nextChan, which has probably shut down and is no longer around to read anything:

```
1470 @ 
github.com/grafana/agent/component/common/loki.NewEntryMutatorHandler.func1+0x18a	/src/agent/component/common/loki/types.go:86
```

cc @tpaschalis

**Comment by rfratto** [comment]
I might've gotten some of the details wrong here.

> which has probably shut down and is no longer around to read anything:

It could also be that the client is just simply blocked and isn't accepting any more samples. Maybe `NewEntryMutatorHandler` should be updated to not wait for the final entry to send when shutting down?

```go
func NewEntryMutatorHandler(next EntryHandler, f EntryMutatorFunc) EntryHandler {
	ctx, cancel := context.WithCancel(context.Background())

	in, wg, once := make(chan Entry), sync.WaitGroup{}, sync.Once{}
	nextChan := next.Chan()
	wg.Add(1)
	go func() {
		defer wg.Done()
		for e := range in {
			select {
			case <-ctx.Done():
				return
			case nextChan <- f(e):
			}
		}
	}()
	return NewEntryHandler(in, func() {
		once.Do(func() { 
			cancel() 
			close(in) 
		})
		wg.Wait()
	})
}
```

**Comment by rfratto** [comment]
This is apparently a known issue in Promtail, with a long history: https://github.com/grafana/loki/issues/2361 

The issue with fixing this is you may drop a log forever, because the positions file may have already updated even if the log line never gets sent to a client. The long-term fix for this is a WAL for logs. 

Short-term, we have to decide between:

* Accepting the fact that this can deadlock the UI and the Flow controller, or
* Permitting the chance of permanently losing the final log entry when shutting down a tailer (until a WAL for logs is added)

**Comment by rfratto** [comment]
Also noteworthy: there is an active PR to add the WAL to Promtail: #7993.

**Comment by tpaschalis** [comment]
> Short-term, we have to decide between:
> Accepting the fact that this can deadlock the UI and the Flow controller, or
> Permitting the chance of permanently losing the final log entry when shutting down a tailer (until a WAL for logs is added)

My 2c on this: I would prefer like losing the log entry, especially since the intent _was_ to shut down the tailer, than allow the controller and Flow UI to be blocked affect a metrics or a tracing pipeline as well.

When we were building the initial set of Loki component we ported over Promtail code with minimal changes (i.e. the positions file also recording the label set) so we can consider some of the alternatives to improve the overall behavior, but I'm personally willing to go for the short-term fix for now.
