### ISSUE TITLE
Expand config file with environment variables

### ISSUE THREAD

**Issue by dcseifert** [grafana/agent#280]
It would be a great feature if environment-variable placeholders like `${<ENVIRONMENT_VARIABLE>}` would be replaced by the environment variable set inside i.e. the grafana-agent container so that configuration values could be applied dynamically.

This would expand a config (assuming that the environment variable `LABEL_A` is set to the value `A_VALUE`) like:
```iml
prometheus:
  global:
    external_labels:
      labelA: ${LABEL_A}
```
to the finally parsed config:
```iml
prometheus:
  global:
    external_labels:
      labelA: A_VALUE
```

**Comment by rfratto** [comment]
Hi, thanks for taking the time to create this issue (and the subsequent PR at #281). This has been discussed before in the #agent channel on the Grafana Slack, but the history is gone now. I appreciate that you made this, since it's a common request and it'll be good to have a URL to point people at. 

Environment variable substitution is a tricky problem that is hard to guarantee correctness of. For example, what if a user has a password they cannot change that just so happens to look like an environment variable pattern? 

Substitution has been [discussed](https://github.com/prometheus/prometheus/issues/2357) at length in the Prometheus project and a [formal vote](https://groups.google.com/g/prometheus-developers/c/tSCa4ukhtUw/m/J-j0bSEYCQAJ) took place last year, where the consensus was to turn down the proposal. prometheus-team doesn't govern this project, but given the similarities I'm inclined to take their decision and reasoning very seriously here. 

In general, I definitely see the value and convenience in processing the config file at runtime, but I don't think it necessarily absolutely _needs_ to happen at runtime. The advice I've given people so far has been to use an `initContainer` to mutate the config file as they see fit. I think that's a decent workaround given the different requirements people may have. ([gomplate](https://github.com/hairyhenderson/gomplate) is a good candidate for running as an `initContainer`).

**Comment by dcseifert** [comment]
Hi, thanks a lot for your quick reply! 

The discussion from the Prometheus project is also very interesting, but I think that initContainers are limiting the usage of this feature to k8s only and introduce a lot of initial complexity when the main task is to "just substitute some values" in the configuration. Actually I see this feature in a lot of tools (i.e. also [Loki](https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration)).

Would disabling this feature by default (to avoid unexpected behavior) and enabling it via a switch be a valid option here?

**Comment by rfratto** [comment]
Right, `initContainers` was just the Kubernetes example, but my point was more that any system should have some kind of mechanism to preprocess files that can stand in for this.

In any case, I didn't know Loki and Cortex recently introduced this, thanks for pointing that out. Given that, I'm going to backpedal: I'd prefer to be consistent with those projects and support this after all. I would like to mimic the Loki implementation (as you've pointed out), but I'll say that in the review to #281. 

Thanks again!
