### ISSUE TITLE
(helm) grafana-agent `faroPort` should be optional 

### ISSUE THREAD

**Issue by nabadger** [grafana/agent#2957]
Hi

https://github.com/grafana/agent/pull/2922 introduces ingress support for faro.

This exposes the agent `faroPort` on the generated service and pod resources which it probably shouldn't do if faro is not enabled (via config in `app_agent_receiver_configs`).

---

A sidenote here is that multiple faro-ports could actually be exposed since `app_agent_receiver_configs` is a list. That could lead to multiple ingresses or a single ingress with multiple backends.

It's not really clear what the recommend setup should be here, i.e: multiple grafana-agents with a single faro-endpoint defined, or 1 grafana-agent with multiple endpoints defined.

**Comment by rfratto** [comment]
Thanks! My gut feeling is that for now, we should probably split `agent.faroPort` into `agent.faro.enabled` and `agent.faro.port` to make it opt-in. 

> A sidenote here is that multiple faro-ports could actually be exposed since app_agent_receiver_configs is a list. That could lead to multiple ingresses or a single ingress with multiple backends.
>
> It's not really clear what the recommend setup should be here, i.e: multiple grafana-agents with a single faro-endpoint defined, or 1 grafana-agent with multiple endpoints defined.

I [mentioned in a comment](https://github.com/grafana/agent/pull/2922#discussion_r1100335918) that we may need a longer term solution for this, since you're right: you may need multiple ingresses for multiple Faro endpoints (and potentially ingresses for non-Faro endpoints). 

Finding a way to make 1 grafana-agent installation feasible with multiple exposed endpoints is ideal, IMO. 

I'm not sure Faro should be mentioned in the Values at all, honestly. Given there's so many things you could potentially configure in Grafana Agent that open up new listen addresses, it might make sense to decouple it into:

* Exposing the Faro port via `agent.extraPorts` 
* Finding a different way to allow specifying multiple ingresses in the values, or assume that ingresses will be applied manually outside of the Helm chart. 

cc @ts-mini, since you opened #2922.

**Comment by nabadger** [comment]
> Exposing the Faro port via agent.extraPorts

In my own setup, this is exactly what I'm doing, as well as generating `agent.extraPorts` from the listeners defined in `app_agent_receiver_configs` (although this is handled with jsonnet ontop of Tanka/Helm).

The ingress part is rather custom as you say...
