### ISSUE TITLE
When replaying the WAL the ".series" records can be missing an entry for a series which is present in the WAL

### ISSUE THREAD

**Issue by replay** [grafana/agent#297]
If that happens then the agent emits the following error message:

```
found sample referencing non-existing series, skipping
```

We currently don't know for sure yet what is causing this, @rfratto says it may be a race condition between a new sample coming in while concurrently a series gets deleted from the WAL.

**Comment by rfratto** [comment]
I've also seen a user report a series mysteriously disappearing from the WAL even though the underlying target is still getting scraped, and other series from that target stay in the WAL. I believe that might be the underlying cause of this.

**Comment by rfratto** [comment]
I've done some investigative work on this. As far as I can tell, the only reason why samples could exist in the WAL for a series that has been deleted is if the series was removed from the WAL despite still existing in memory.

I've been able to reasonably discount hash collisions (which I am confident are handled gracefully and couldn't cause this even if they weren't). After a few hours and a lot of mental gymnastics, a race condition between two concurrent instances are the only thing I've been able to see as a potential root cause. 

1. Hypothetically, there are two Agent instances running concurrently. Instance B is in a bad state where it is unable to append samples for a subset of series properly. Instance G is behaving normally. Both instance B and G are scraping the same jobs and writing to the same WAL. Instance G must have spawned after B and thus share many of the same ref IDs.
2. A deadlock or some other flaw is preventing instance B for updating the most recent written timestamp for one shard of series. This would affect between one and 1/16384th of total series. 
3. Instance B continues to perform the WAL checkpointing every minute, and eventually deletes series that it believes have not been written to. 
4. Meanwhile, instance G continues to append duplicate samples for the same series successfully. 
5. That series, despite getting new samples, is now deleted from the WAL and will disappear from the remote_write system. 

I'm not happy with this theory; it's too many ifs and it's hard to prove that step 2 is possible. I think we need to wait for this to happen again and get more information about the job where the series is missing (how often is it getting scraped?) and the environment (can we tell if multiple agents with the same config are running on the same machine? Is it possible the same instance is running twice?)
