### ISSUE TITLE
Using AWS tags and meta with agent integrations

### ISSUE THREAD

**Issue by KVInventoR** [grafana/agent#303]
Hi All,

Unfortunately  I didn't find any possibility to use __meta_ec2 information with integrations in section labels,
Is it possibly to use __meta in any section like as: metric_relabel_configs with integrations?

I would like to add dynamically EC2 tags as metrics labels for all integrations for local agent.

**Comment by rfratto** [comment]
Hey there, unfortunately it's not clear how we would support this. There's no service discovery being used for the integrations, since the Agent is generating the metrics itself. 

v0.9.0 supports using environment variables in the config file; do you have the EC2 metadata you want available as environment variables?

**Comment by KVInventoR** [comment]
I think environment variables is good for me.
But also, probably it will be useful to have something like:
pre_run_script in agent configuration, which can run call during start agent and export some environment variables, which will be possible to use in dynamic configuration.


I will try to read more about environment variables intergration
Thank you
