### ISSUE TITLE
Agent configuration on Kubernetes

### ISSUE THREAD

**Issue by alexangas** [grafana/agent#316]
Hello! I'm quite new to Kubernetes deployments and also Prometheus, etc. (but like the goals of Grafana Cloud Agent). Unfortunately I'm struggling with joining the dots on the documentation. Could you please take a look at a few questions which, as mentioned, are probably quite newbie - so apologies in advance...

The repo README (and elsewhere) mentions the install script as an easy way to get started. This is true in a sense as immediately the "scrape_duration_seconds" metric started populating in Grafana Cloud. However I can't find data coming in for any other metrics. Should it be?

I'm very keen on having node-exporter metrics coming through. I can see this described as being enabled through the "integrations" YAML node. However when I review the agent.yaml, I'm not sure where to include this. There is YAML for ServiceAccount and ConfigMap which both contain similar content. What is the difference / which should be updated? I tried adding to both and nothing seems to be happening.

Is there any particular procedure for upgrading the agent after a configuration change, or between versions? Is it just a matter of re-running the install script again?

Finally, does the Agent happily scrape all pods in the cluster without any additional configuration?

**Comment by rfratto** [comment]
Hey there, I'm happy to help! Documentation for people that are new to the Prometheus world is one of our weakest points right now, especially within Kubernetes. Don't feel about about any questions you might have, since your experience is going to help us improve our documentations and help others down the line.  

> However I can't find data coming in for any other metrics. Should it be?

You should at least be getting all Agent metrics out of the box - if you query for `up` you'll see all targets the Agent is currently scraping. 

> I'm very keen on having node-exporter metrics coming through. I can see this described as being enabled through the "integrations" YAML node. However when I review the agent.yaml, I'm not sure where to include this. 

Unfortunately the default installation might not be very good at this, but we can make the changes necessary to get it to work. First off, you'd need to add:

```yaml
integrations:
  node_exporter:
    enabled: true
    rootfs_path: /host/root
    sysfs_path: /host/sys
    procfs_path: /host/proc
```

to the root level of your overall agent YAML config (i.e., on the same indentation level as `server` and `prometheus`).

Next, you'll want to bind mount the following locations from the host machine to the container: `/` to `/host/root`, `/sys/` to `/host/sys`, `/proc` to `/host/proc`. There's an example of how to do that in Kubernetes [in the config reference](https://github.com/grafana/agent/blob/6cf3d9eb392fe9136c60e21854daf92275c8f451/docs/configuration-reference.md#node_exporter_config), but let me know if you need more help with it. 

> Is there any particular procedure for upgrading the agent after a configuration change, or between versions? Is it just a matter of re-running the install script again?

You can re-run the install script, but that's going to override any changes you make to the ConfigMap. Once you've installed the agent, I'd just recommend changing the image version. We're currently trying to keep everything backwards compatible, but keep an eye out for the release notes before updating just in case we have to make an exception. 

> Finally, does the Agent happily scrape all pods in the cluster without any additional configuration?

This is definitely the thing we need better docs around the most. The Agent config provided with that install script doesn't scrape just any pod. It looks for pods that conform to the following rules:

1. The pod must *not* have an annotation matching `prometheus.io/scrape: "false"` (this wouldn't be there unless you explicitly add it or if you deploy a Helm chart that has it).
2. The pod *must* have a port with a name ending in `-metrics`. This is the port that will be scraped by the Agent. A lot of people using Helm struggle with this, since Helm charts don't usually follow this. You would need to add a new scrape config to scrape helm charts or find a way to tweak the Helm chart to follow this rules. 
3. The pod *must* have a label named `name` with any non-empty value. Helm usually lets you add extra labels, so this is less of a problem for Helm users. 
4. The pod must currently be running. (i.e., Kubernetes must not report it having a phase of Succeeded or Failed).

This is a lot of rules that are written in the scrape config but not converted anywhere into English (until now, I guess!), and unless you have full control over what you're deploying, it can be difficult to get things to align to these rules. I'll definitely be willing to help you write custom rules for your environment. You can also try asking in the [Grafana slack's #agent channel](https://slack.grafana.com/) for help, where other users can give you answers and so you're just not waiting around for specifically a maintainer to help. 

I hope this helps, and let me know if there's anything else I can do!

**Comment by alexangas** [comment]
Really appreciate your open and welcoming approach! I've made a little bit of progress in that I confirm the metrics coming in to Grafana appear to be those you describe.

Regarding updates to the [Kubernetes agent.yaml](https://github.com/grafana/agent/blob/v0.9.1/production/kubernetes/agent.yaml), I've added the node_exporter snippet provided. This is recognised as the logs show the expected failure of not being able to find those folders you have listed.

I've attempted to add the mounts snippet from the config reference in a few different ways. (By the way there seems to be a typo of `priviliged` instead of `privileged`). These have been to:
1. Add the snippet as-is to the bottom of agent.yaml which fails as it cannot find `config.file`, whether I use the path in the snippet or the one elsewhere in agent.yaml.
2. Add the `securityContext`, `volumeMounts`, and `volumes` to kind `DaemonSet` which didn't appear to bind mount folders.
3. Add the `securityContext`, `volumeMounts`, and `volumes` to kind `Deployment` which didn't appear to bind mount folders.

I'm now a member of the Slack #agent channel so will see if there's anything there that may help as well.

**Comment by rfratto** [comment]
Ah, thanks for pointing out the typo! That example probably isn't very good since it doesn't align with the existing config that the real manifest uses.

I've created a [gist](https://gist.github.com/rfratto/5fcaceb12324b401e8c73be63186d052) that enables node exporter and adds the appropriate volume mounts; check it out and let me know if it helps. 

(FYI, we're investigating building a Kubernetes Operator over the next 4-6 months which should make deploying the Agent on Kubernetes significantly easier)
