### ISSUE TITLE
Cloud Agent as a daemonset

### ISSUE THREAD

**Issue by jplouis** [grafana/agent#324]
I'm new to Prometheus and Grafana and have been looking at options for migrating our K8S usage of Prometheus to include Cortex. We continue to vertically scale Prometheus and are also looking to shard it to reduce load. 

Has there been any discussion on the viability of running the Cloud Agent as a daemonset on K8S that only scrapes pods on the same node? Is the agent resource usage small enough to do so? In the end I'm looking to reduce the operational overhead of making sure our singleton Prometheus servers have enough resources and reduce the complexity of having to shard Prometheus within a single K8S cluster.

**Comment by rfratto** [comment]
Hi, this is a mode we already support through [host filtering](https://github.com/grafana/agent/blob/master/docs/operation-guide.md#host-filtering). 

When you deploy the Agent as a DaemonSet with host filtering enabled, every Agent across the whole cluster still will be querying the Kubernetes API. It will start to put strain on the cluster once you hit hundreds of nodes, and adds some overhead since every pod is still doing the same service discovery in front of the filter. If your goal is to distribute the resource usage though, it should help. 

We've currently been planning a second iteration of our operational clustering mechanism that will address some of these problems:

- Remove the dependency on the separate KV store that the current clustering mechanism requires, use gossip and config files instead 
- Distribute service discovery responsibility amongst the Agent cluster 
- Distribute scrape responsibility per-target amonst the cluster.

Hypothetically, you could deploy this second iteration of the scraping service as a Deployment or a DaemonSet, but it wouldn't necessarily only scrape pods running on the same node as the Agent anymore. This is the mode I'm really interested in supporting in the future over the host filtering mechanism, as having the Agents collaborate will open the door for a lot of cool features down the line.

**Comment by jplouis** [comment]
Thank you for the response. It was exactly what I was looking for and look forward to the future enhancements.

Cheers.

**Comment by rafilkmp3** [comment]
How I can change agent to use daemonset instead single instance to scrap all ?? using grafana operator ?
