### ISSUE TITLE
grafana-agent stuck in "Remote storage resharding"

### ISSUE THREAD

**Issue by azadsagar** [grafana/agent#3287]
We recently upgraded memory for our agent to 64 to 200gig.
grafana-agent version we are using is 0.30.2.
Our agent is stuck with `remote storage resharding`, it seems a dead lock as it keeps logging `"Remote storage resharding" from=4 to=2`, `"Remote storage resharding" from=2 to=1` and keeps on repeating on it's own.

**Comment by rfratto** [comment]
The log messages here indicate that the remote_write system thinks it needs a different number of shards to send backlogged metrics to the endpoints. It's a normal operation for it to change based on the current load of incoming metrics to the WAL and the write latency to the remote_write endpoints.

Given this, we don't believe this is a bug or the agent is "stuck," but rather just that the scrape load or response latency from the server is inconsistent. 

I'm going to close this issue for now since it's been opened for a while, but if you have more information about why you believe the agent is stuck, please feel free to open a new issue with more information.
