### ISSUE TITLE
Proposal: add optional second argument to env() stdlib function

### ISSUE THREAD

**Issue by dosmanak** [grafana/agent#3389]
[env()](https://grafana.com/docs/agent/latest/flow/reference/stdlib/env/) function returns empty string if environment variable is not defined.

I've found the implementation is pure go [os.Getenv()](https://github.com/grafana/agent/blob/main/pkg/river/internal/stdlib/stdlib.go#L21).

I propose to implement custom `env()` function with optional second argument as `env("POSSIBLE_VAR","reasonable default")` so the configuration can be finetuned using environment variables.

**Comment by rfratto** [comment]
To make this not a breaking change, we'd probably want do this by one of:

* Add a new function that is some form of `env_or_default`
* Adding support for optional arguments (I'm not sure about this being a good idea)
* Rely on #2638, even if it's verbose, it would enable this use case 
* Have some kind of `or` function similar to Go templating where it will use the first non-zero value, so that `or(env("VAR_DOES_NOT_EXIST"), "default_value")` could be used.

**Comment by rfratto** [comment]
Another option would be supporting an `envsubst` function to allow Bash-like syntax for defaulting and other patterns:

```river 
envsubst("${POSSIBLE_VAR:-reasonable default}")
```
