### ISSUE TITLE
Proposal: Allow for dynamic addition of new discovery components.

### ISSUE THREAD

**Issue by captncraig** [grafana/agent#3655]
### Background

The current pattern for defining discovery targets and scraping their metrics looks something like this:

```
discovery.kubernetes "pods" {
  role = "pod"
}
discovery.kubernetes "services" {
  role = "service"
}
prometheus.scrape "scraper" {
  targets    = concat(
    discovery.kubernetes.pods.targets,
    discovery.kubernetes.pods.services
   )
  forward_to = ...
}
```

This works ok for small numbers of targets, but when the list gets large it can feel rather cumbersome maintaining a large list of targets. Additionally, as we consider modules or remote config, it becomes harder to add additional targets in a clean way. You cannot provide a clean, pasteable snippet for a discovery component, since you also have to modify an existing scrape component.

### Proposal

My primary goal is to allow new discovery components to be added without having to change any existing components. There may be other places in the code base where similar issues apply, but I am mainly focused on discovery. 

Possible solutions:

1: Reverse the direction of data flow so that discovery components "push" their targets into a scraping (or other) component by referencing it (breaking change).
2. Provide some sort of dynamic discovery so downstream components can find relevant discovery components and aggregate their targets.

### Option A: Change data flow direction

If we were designing flow components today, I would push harder for a flow like:

```
prometheus.scrape "default" {
  forward_to = ...
}
discovery.kubernetes "pods" {
  role = "pod"
  forward_to = prometheus.scrape.default.targets
}
discovery.kubernetes "services" {
  role = "service"
  forward_to = prometheus.scrape.default.targets
}
```
Things that are nicer about this:
- All data flows in same direction. You can order your file so that things referenced are defined above their usages, and the order matches the way data moves through the system.
- You can add snippets without altering anything else.

Big thing that is not so good:
- It is a breaking change to everybody.

Possible middle ground would be adding *both* a push-based and a pull-based mechanism for moving targets, but then everything is more complicated and error-prone. But at least people can use it how they want to.

### Option B: Dynamic component discovery

It might be nice to be able to get a list of components as an expression, and filter or aggregate across it to build an expression for what you need. Probably much more useful in conjunction with something as proposed in #2783.

Perhaps you could do something like this (syntax being placeholders for now):

```
prometheus.scrape "default" {
  // find all discovery.* components that have a field "scraper" set to "default", and aggregate their targets.
  targets = find("discovery.*", func(d) => {d.scraper == "default"}).map(func(d){d.targets}),
  forward_to = ...
}
```

This could be very powerful, and lead to many more use cases than just the one I've outlined above.

**Comment by Chewie** [comment]
Currently, the design of the components is not consistent, with some expecting a targets arguments and others waiting to be pushed to, and relabeling components using a different name for their exported fields (`output`  instead of `targets`).

While this is indeed a big breaking change, I think moving all components to a push design would in the long run simplify both the final config file, with the added benefit of dynamic addition, and the learning process by reducing surprises.

If this inconsistency is seen as a paint point, the best moment to address it would be now while the project is still young and moving fast, and before people massively switch from the operator or static mode to the flow mode.

My 2 cents,

**Comment by rfratto** [comment]
I have three concerns with globally forcing a single direction for component data flow: 

1. Debuggability  
2. Future expressiveness
3. Maintenance burden 

Even though the design is inconsistent, there is benefits to debugging: you can see targets by looking at the exports of `discovery.kubernetes` and the arguments of `prometheus.scrape`. If we move to a push-only design, then we would have to put extra work into making sure that the debug information for components contains everything you may be interested in.  

Also, doing a push-only design means that we're never passing data between components any more, but rather just connecting their signals. This would make things like #2783 less useful, where I want to allow expressions to be used to mutate data. Allowing expressions to mutate data means that users depend less on maintainers to use cases via components, as users would have the ability to mutate data themselves.

Furthermore, I'm concerned that a push-only design will be prone to leaking: if a push-based `discovery.kubernetes` component terminates, all of its targets should disappear from anything it's connected to. We should make it _extremely_ hard, if not impossible, to write push-based components incorrectly. 

I'm not concerned about leaking with `prometheus.scrape` pushing to `prometheus.remote_write`, because those pushes are events, but `discovery.kubernetes` isn't; Discovery components are declarative and reflect the current state of Kubernetes. 

I'm not fully against changing the design, but I'm worried that the trade-offs aren't worth it just for the sake of consistency.

**Comment by captncraig** [comment]
I think I am willing to close this as it stands because it isn't strictly needed as-is to make good modules. You can get the same effect by creating your discovery and scrape components in a module and forwarding to the shared receiver. Unless we find a problem with having multiple scrape components vs a single one, let's see how far the existing pattern can take us.

I feel like maybe we will find more cases for dynamic discovery of things in the future, but lets hold off on this until we find some.
