### ISSUE TITLE
Integrations assume HTTP Agent server

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#368]
The integrations system currently assumes that the Agent's HTTP server is not using HTTPS. Enabling HTTPS will cause integrations to fail to scrape. 

Related to #367.

**Comment by ealmonte32** [comment]
Is this with regards to the locally installed / localhost grafana agent or the one that sends data to the grafana.net cloud via agent?
Enabling HTTPS fails because there is no self signed certificate on the device?
Want to help contribute with this if possible but would like a but more info/details on the exact issue.
I guess in terms of workflow, if you could explain the workflow that leads to this issue that would help me try and understand it and maybe replicate the error in order to find a workaround.

**Comment by rfratto** [comment]
Sure! This applies to any deployment of the Agent regardless if it's sending to localhost or otherwise. We use the [Weaveworks common server](https://github.com/weaveworks/common/blob/master/server/server.go#L45:6) which supports configuring the server as HTTPS. Users may want to ensure the Agent only uses HTTPS in secure enterprise environments. 

The integrations system works by dynamically configuring a scrape job for the Agent to scrape itself. The problem is that it will always assume the Agent's server is *not* using HTTPS, so it will fail to connect to itself. We need the integrations system to use https if the Agent server is also using https.

**Comment by ealmonte32** [comment]
Oh ok so this seems more like a self-reminder for you, since I dont know Golang I would assume though that the integration can either check what port the agent is using through initial agent installation or maybe require a variable like GCLOUD_STACK_ID but instead simply GAGENT_HTTPS=0 or =1 so that the agent and any integration have a common variable to look for..? 🤷🏻‍♂️
