### ISSUE TITLE
question: memory usage of sharded agents

### ISSUE THREAD

**Issue by yurii-kryvosheia** [grafana/agent#3705]
We are trying to distribute resource utilization on different node instead of using one huge node with one grafana-agent replica.
No matter what number of shard we use it always results in shard*replica number of agent pods with the **same amount of RAM** usage as the one agent with one shard. 
We hoped to see lower number in RAM usage on every agent due to distribution of scraping targets but it stays the same. 
Is it exepected by design?

**Comment by tpaschalis** [comment]
How are you sharding the targets?

If using [hashmod sharding](https://grafana.com/docs/agent/latest/static/operation-guide/#hashmod-sharding-stable), are you properly applying the hashmod relabel_configs? 

Equal memory usage sounds to me like that the number of targets are _not_ getting distributed due to the above. Could you hit `/agent/api/v1/metrics/targets` from the [Agent API](https://grafana.com/docs/agent/latest/static/api/#list-current-scrape-targets-of-metrics-subsystem) to verify the number of targets being picked up by each node?

**Comment by yurii-kryvosheia** [comment]
We have no static scrape configs, only service/podMonitor, so relabel_configs is handled by the operator.
Confirming than number of targets on each agent is different. Also checked those targets are unique and doesn't repeat on each agent.
