### ISSUE TITLE
agent scraping mode doc is sitting at the wrong level in the doc tree

### ISSUE THREAD

**Issue by robertvandervoort** [grafana/agent#3827]
### What's wrong?

The agent scraping mode doc https://github.com/grafana/agent/blob/main/docs/sources/static/configuration/scraping-service.md
is siting inside the static mode section. since it is one of the modes, like static mode, and agent flow also has its own spot in a higher level, shouldn't this also be similar? It is kind of hidden.

### Steps to reproduce

Open the doc page at https://grafana.com/docs/agent/latest/static/configuration/scraping-service/

look on the left menu and see where the scraping service mode sits as the last element in the static mode config section.

**Comment by rfratto** [comment]
We need to change the terminology for how we describe scraping service, since we changed the meaning of mode to mean "deployment variant," of which static mode, Flow mode, and the operator are the only three deployment variants.  

Scraping service doesn't fall that category, so we'll need to find a new way to describe it. I do personally think it belongs in the configuration section, and I don't mind that it's hidden since we don't recommend people using it unless they really know what they're doing and understand the trade-offs.

**Comment by clayton-cornell** [comment]
@rfratto Would it be enough here to simply drop `mode` from the topic and call this the Scraping service? And... rephrase the opening description to `The Grafana Agent scraping service allows you to cluster a set of Agent processes and distribute scrape load.` There are a few other that would require some tweaking to rephrase and remove "mode"

**Comment by rfratto** [comment]
@clayton-cornell Yes, I think dropping "mode" is a good idea, since the meaning of "mode" changed since we first launched the scraping service.
