### ISSUE TITLE
Generated name is too long

### ISSUE THREAD

**Issue by james-callahan** [grafana/agent#3937]
### What's wrong?

Grafana Agent Operator attempts to use a name longer than the kubernetes maximum length.

### Steps to reproduce

Create a `LogsInstance` and `Integration` that has a volume. The length of the namespace + the length of the integration name should be of non-trivial length.

### Software version

v0.33.2

### Logs

```text
level=error ts=2023-05-22T03:25:36.856221756Z controller=grafanaagent controllerGroup=monitoring.grafana.com controllerKind=GrafanaAgent GrafanaAgent=grafana-agent-operator/grafana-agent-logs namespace=grafana-agent-operator name=grafana-agent-logs reconcileID=67d74ba0-0bcd-4261-aa9a-4d182a1341a2 msg="error during reconciling" err="failed to reconcile integrations Deployment: failed to create Deployment: Deployment.apps \"grafana-agent-logs-integrations-deploy\" is invalid: [spec.template.spec.volumes[3].name: Invalid value: \"grafana-agent-operator-grafana-agent-eventhandler-agent-eventhandler\": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[3].name: Not found: \"grafana-agent-operator-grafana-agent-eventhandler-agent-eventhandler\", spec.template.spec.containers[1].volumeMounts[3].name: Not found: \"grafana-agent-operator-grafana-agent-eventhandler-agent-eventhandler\"]"
```
```

**Comment by marctc** [comment]
Thanks for reporting, and sorry for taking so long to look into it.

Looks like is a limitation from [Kubernetes](https://stackoverflow.com/questions/50412837/kubernetes-label-name-63-character-limit). We can't change the way that prefixes are made because with this way we prevent collisions with CR names. 

I don't see an easy way to fix other than use shorter names for namespace and integration. I'm more inclined to close this issue as it's something we probably won't have capacity to work on at this moment. Feel free to reopen it if you can come up with an easy solution :pray:
