### ISSUE TITLE
content should be one of [number string] for binop +, got capsule

### ISSUE THREAD

**Issue by jkroepke** [grafana/agent#4036]
### What's wrong?

Concat string through `+` operator wont work, with responses from a flow component like http.remote

### Steps to reproduce

1. Create a config file like described below.
2. Start agent

### System information

MacOS 13.4

### Software version

v0.33.0 + main

### Configuration

```text
// Fetch resourceId from IMDS
remote.http "imds_resource_name" {
    url            = "http://169.254.169.254/metadata/instance/compute/name?api-version=2021-02-01&format=text"
    headers = {
        "Metadata" = "true",
    }
    poll_frequency = "86400s"
    poll_timeout   = "1s"
}

remote.http "config_default" {
    url            = "https://exmaple.com/grafana-agent/config/default/"+remote.http.imds_resource_name.content+".river"
}
```

### Logs

```text
remote.http.imds_resource_name.content should be one of [number string] for binop +, got capsule
```

**Comment by rfratto** [comment]
Some background for why this is happening:

Any time documentation says something is a "string or secret," it's actually (internally) treated as a capsule value called [OptionalSecret](https://github.com/grafana/agent/blob/a82513e79c7df0713654d4fc5d05f07c424f547f/pkg/river/rivertypes/optional_secret.go#L11-L35). 

The OptionalSecret capsule supports being converted from/to strings and secrets, but that conversion clearly isn't happening in the context of a binop. 

The reason it's done this way is because it's not possible for a Flow component to change the type of value it exports, so we used a capsule value to represent the combination of both. 

Meanwhile, Terraform takes a slightly different approach: go-cty values (the value/type system used by HCL) can have flags to mark something as sensitive, which isn't something we support for performance and ease-of-usage reasons. 

I think this breaks down into a few problems:

1. It's potentially a mistake that we're not being honest about what the type is (OptionalSecret) and instead just saying it's either a "string or a secret," even though it can't act like either in the case of binary operations. 

2. Type conversions from capsules aren't happening with binary operations. Conversions will happen if you try to add a string to a number (`"Hello world" + 5` will be `"Hello, world5"`), but not with any capsule values which support conversion. 

3. There's no other way to attempt to coerce a value into a string, like with a `to_string` function. 

A `to_string` function would be the easiest workaround here while the type conversion issue gets worked out. I'm not sure how useful `to_string` would be after the type conversion issue is resolved, but it'd be fairly harmless to have either way. 

My suggestion would be that we start with a `to_string` conversion function to offer a workaround to this, and in the longer term figure out if binary operations should attempt to do implicit conversions like assignment does. 

cc @clayton-cornell for opinions on the documentation front (for problem 1 listed above)
cc @grafana/grafana-agent-core-maintainers for opinions on the proposed path forward for now.

**Comment by jkroepke** [comment]
Since version 0.34, a workaround exists:

```
remote.http "config_default" {
    url            = "https://exmaple.com/grafana-agent/config/default/"+nonsensitive(remote.http.imds_resource_name.content)+".river"
}
```

**Comment by ptodev** [comment]
If we cannot think of an easy way to make OptionalSecret truly behave like a secret or a string, then IMO we should just document it as a type like `optionalSecret` or `sensitive` (instead of [saying](https://grafana.com/docs/agent/latest/flow/reference/components/remote.http/#exported-fields) "string or secret"), which would then allow us to also document how that type behaves.

On a more general note, even if we make OptionalSecret behave like either a string or a secret, I'm not sure if that's a generic enough solution. What if the user wants `remote.http` to return a `number`, `bool` or even a `list(string)`? It might be good sometime to have a more generic way to augment the exported types of components. Then the same solution could be used in the OptionalSecret case to augment it into a string or something else.

**Comment by clayton-cornell** [comment]
I can't add a lot on the technical side of the type conversion challenge. From docs side though, we do have to be very careful around anything to do with statements related to securing user secrets and expectations... especially if the assumed behaviour isn't what is really happening.
