### ISSUE TITLE
loki.process stage which merges given labels to the log line

### ISSUE THREAD

**Issue by akselleirv** [grafana/agent#4111]
### Request

Discussion started in Slack thread https://grafana.slack.com/archives/C01050C3D8F/p1686237967379259

Add a stage in `loki.process` which takes a set of labels and adds them to the log line. My initial use case was to add it to a JSON object, but it could be more generic add make it possible to use it with logfmt and possibly an unstructured format by appending.

### Use case

The GeoIP stage in `loki.process`  the values to labels, but I want to add it to the log line itself.

An example which add a set of labels to a JSON object: 

```
Log line:  {"msg":"log message","user":"a-user"}
Labels: { "level" = "error", "env" = "dev","user_id" = "f8fas0r"}

stage.merge {
    labels      = [ "env", "user_id" ]
    source_type = "json"
}

transforms to:
Log line: {"msg":"log message","user":"a-user","env":"dev","user_id":"f8fas0r" }
Labels: { "level" = "error" }
```

**Comment by rfratto** [comment]
cc @tpaschalis for thoughts on this

**Comment by akselleirv** [comment]
Closing this issue as I can use the `stage.pack` for this use case. Only drawback that I need to use `unpack` in Loki when querying for these logs.

**Comment by tpaschalis** [comment]
Caught up offline and verified that the `pack` stage can work in a similar fashion, without having to worry about the structure of the log line itself, and offloading the effort of working with the extra labels to query time.

One thing that came out of that conversation, is that since the initial labels _do_ exist in the shared extracted map, we could see a pair of`jsonmerge/logfmtmerge` stages that work on values from the extracted map and have well-defined merging semantics being generally useful.

In coordination with the `output` stage, it would also be able to support the original use case from here.

I'm leaving it to you @akselleirv if you'd like to re-open the issue with a focus on a `merge` stage that works on the extracted values map, or if you'd prefer that we open a new issue to start the discussion there.
