### ISSUE TITLE
remote.s3 loads empty content

### ISSUE THREAD

**Issue by timo1707** [grafana/agent#4134]
### What's wrong?

when running a [remote.s3](https://grafana.com/docs/agent/latest/flow/reference/components/remote.s3/) component in the config.river, on some polls the content of the remote module.river is not being read and returns a empty string while the component keeps "healthy" and no `agent_remote_s3_errors_total` return no error count.

### Steps to reproduce

running below config with remote module.river 

### System information

WIN10 x64

### Software version

v0.34

### Configuration

```text
remote.s3 "default" {
  path = "s3://redacted/metrics/module.river"
  client {
    endpoint = "http://bucket.vpce-redacted.s3.eu-central-1.vpce.amazonaws.com"
    region = "eu-central-1"
    signing_region = "eu-central-1"
  }
}
module.string "default" {
	content = remote.s3.default.content
}
```

**Comment by rfratto** [comment]
Thanks for reporting. This sounds similar to the discussion that was had in https://github.com/grafana/agent/issues/4084#issuecomment-1581288175:

> Yeah, this is component best practices IMO: a component which retrieves external state should fail on construction if it fails to retrieve that state. This is what local.file does; the component will fail to build if its initial config points it at an invalid file.

Looking at the code, remote.s3 only ever polls in the background, and won't fetch new files on update or construction. IMO that should change to behave so that it behaves like local.file and (as of #4103) remote.http.
