### ISSUE TITLE
Grafana Agent Flow: Fetching basic_auth credentials from env in Blackbox Exporter config file

### ISSUE THREAD

**Issue by ishantanu** [grafana/agent#4301]
### Request

Hello,

I was wondering if it is possible to fetch `basic_auth` credentials from environment variables (or any other way) and substitute  them in `blackbox_exporter`'s config.

I was looking at `local.file` and `env` function in the docs but wasn't sure how that'd work in this case.

Please let me know if this is already possible as I wasn't able to find any example of this.

### Use case

I don't want to store the username and password for basic auth in plaintext in `blackbox_exporter`'s config file.

If the credentials can be somehow templatised and replaced during the loading of config file in `prometheus.exporter.blackbox` block, that'd remove the need for storing sensitive data in plaintext.

**Comment by ptodev** [comment]
Hi, thank you for reporting this. I just realised something else as well - even if we could use the "config" argument in [prometheus.exporter.blackbox](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.exporter.blackbox) instead of the "config_file" one, there is a security problem because "config" is of type "string" rather than "secret" or "optional secret". I raised #4302 for this issue just now.

In order to fix your immediate problem, would it not be possible to specify the password via the "password_file" field instead of "password"? Judging by the blackbox [config format](https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md), this should be possible.

**Comment by marctc** [comment]
Thanks for reporting. I'll look into it together with @ptodev issue.

**Comment by marctc** [comment]
Hey @ishantanu,

I was looking at this but it would be tricky to implent as `config` is the embeded config from blackbox exporter itself and not a river block. Is this not an option?

```
local.file "config" {
    path = "blackbox_config.yml"
    is_secret = true
}

prometheus.exporter.blackbox "example" {
    config = local.file.config.content

    target "network_switch_1" {
       ...
    }
```

**Comment by marctc** [comment]
After merging this [PR](https://github.com/grafana/agent/pull/4362), the Flow UI will hide the config if you configure it how i mentioned before.

**Comment by ishantanu** [comment]
Hi both, apologies for the delayed response. I haven't tried your suggestions yet. I will give it a try and will let you know which works.

**Comment by marctc** [comment]
@ishantanu I'm closing the ticket. Please reopen it if my proposal doesn't work for you, thanks!
