### ISSUE TITLE
add up metrics for instance scrape status

### ISSUE THREAD

**Issue by yuecong** [grafana/agent#45]
Can we add
```
up{job="<job-name>", instance="<instance-id>"}
```
into this agent? This metrics is especially useful to monitor any scrape failure. Any alternative metrics we can use if some concern to add `up` metrics into the agent?

My one use case on this is to confirm which agent is scraping what set of pods. This is especially helpful to confirm sharding works.

**Comment by rfratto** [comment]
Hi, I think this would be useful to have. As far as I can tell, this wouldn't be too easy to implement without changing Prometheus - the best we could add into the Agent without any upstream changes is a flag that always injects the instance name as a label for every scraped target. That might be more than what you want, though. 

@gouthamve Any thoughts on this? I could be missing something obvious, but it seems like we need to be able to add custom labels to the scrape loop's report sample mutator. Any other options short of what I suggested above and/or exposing the mutator for the agent to use?

**Comment by yuecong** [comment]
yep. if we could get some metrics on the agent similar to [this](https://prometheus.io/docs/concepts/jobs_instances/), it will help to monitor whether the agents able to scrape all its targets.

**Comment by rfratto** [comment]
sorry, I think I misunderstood your initial question. the agent already has all of those metrics since they're generated by the Prometheus scraper, and I'm seeing all of them in our environment where the agent is deployed. if you're not seeing them, you might want to check your logs for warn messages for `append failed` or `appending scrape report failed`.

what the agent doesn't do is inject a label into these metrics to indicate which agent Prometheus config the targets are being tracked from. after thinking about it more, this can be done without changing Prometheus. this is something that would be useful to have for our "scraping service" mode and I'm going to try to get it in within the next few weeks.

**Comment by yuecong** [comment]
Are those included in the default 80 port? I can not find any of them from `80/metrics` page.
But I can see some metrics from the job level, e.g.
```
rometheus_target_sync_length_seconds{scrape_job="xxx",quantile="0.01"}
```
```
prometheus_target_scrape_pool_sync_total{scrape_job="kubernetes-pods"}
```

but there are no metrics from the instance level.

**Comment by yuecong** [comment]
btw, there is no `*failed*` in my logs and I can see metrics are scraped by them.

**Comment by yuecong** [comment]
nvm. it looks like those metrics are not showing up in `:80/metrics` ( even prom's :9090/metrics), but it is generated and write to the remote write endpoints. Thanks for the answers here. I am going to close this issue.
