### ISSUE TITLE
spanmetrics: wire in new metrics_flush_interval field

### ISSUE THREAD

**Issue by tpaschalis** [grafana/agent#4614]
### Request

Since we've updated our OpenTelemetry Collector dependency, we can now wire in a new field available in the spanmetrics processor, `metrics_flush_interval`.

### Use case

This would help with limiting the rate of metrics generation, from every time a trace was received to a preset interval and help users manage their data throughput.

**Comment by rfratto** [comment]
Is this for both Flow mode and static mode?

**Comment by shelbyatgrafana** [comment]
@rfratto I believe this is just for static mode if I recall correctly. The issue was raised by a user in these tickets: 

https://grafana.zendesk.com/agent/tickets/102974 
https://grafana.zendesk.com/agent/tickets/96729 (where the issue was escalated and created)

I am not sure about flow mode, but if you make any changes to the static agent, I'd love to give this user an update so just let me know :) Thank you thank you!

**Comment by foreverest** [comment]
Hey @rfratto @shelbyatgrafana . I'm the one who raised this. We use static mode, currently.

**Comment by rfratto** [comment]
For development context, anything added to static mode must also be brought into flow mode, since we're actively working on giving flow mode parity with static mode. 

Since the request is for static mode, then the implementation must make sure that both static mode and flow mode are covered.

**Comment by nijave** [comment]
I think this was added here https://github.com/grafana/agent/commit/7357b376ba7bacdd303954646c2e6a8ffe78a851#diff-e2e63ff69ed7490ea189f8053e03be8b6d74504e8b1f8ec5b4c516e07b9daf28R50 ? (in 0.36.1)
