### ISSUE TITLE
Flow: support TLS from the Windows certificate store like in static mode

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#4887]
### Request

Static mode supports using the Windows certificate store for running the TLS server, where the TLS keypair is stored securely in Windows and encryption is deferred to the Windows certificate store using Windows' API.

As part of feature parity with static mode, Flow mode also needs this functionality.

### Use case

To run a TLS server on Windows without storing the TLS keypair as plain files.

**Comment by rfratto** [comment]
This should probably be a component which exports some kind of capsule instead of being embedded directly into the `tls` block like in static mode. This would open the door for other kinds of TLS signers that aren't Windows-specific. 

WDYT @mattdurham?

**Comment by mattdurham** [comment]
Likely would need to override some of the behavior of the `http` configuration block since the code follows a different code path, ie it would replace the inner listener of the pubLis in the current TLS implementation.

Maybe something like
`
http {
   listener = http.tls.windows.certificate_store.store.listener
}
`
and the default if not specified would be the current.

Another route would be to all it to override only the verifypeer and get certificate via some sort of handler.

`
http {
   certificate_handler = http.tls.windows.certificate_store.store.handler
}
`
