### ISSUE TITLE
Script installer overwrites /etc/grafana-agent.yaml

### ISSUE THREAD

**Issue by isavcic** [grafana/agent#553]
Hello,

I attempted to upgrade the already installed Grafana Agent by using the installer script. dpkg realizes that there is the new version provided, so it asks whether to overwrite the already existing config. But, the installer itself overwrites the config nevertheless:

```
--- Using package system deb. Downloading and installing package for amd64
(Reading database ... 227578 files and directories currently installed.)
Preparing to unpack /tmp/grafana-agent.deb ...
Unpacking grafana-agent (0.13.1-1) over (0.11.0-1) ...
Setting up grafana-agent (0.13.1-1) ...

Configuration file '/etc/grafana-agent.yaml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** grafana-agent.yaml (Y/I/N/O/D/Z) [default=N] ? 
--- Retrieving config and placing in /etc/grafana-agent.yaml
integrations:
  node_exporter:
    enabled: true
  prometheus_remote_write:
  - basic_auth:
      password: xxx
      username: yyy
    url: https://prometheus-us-central1.grafana.net/api/prom/push
prometheus:
  configs:
  - name: integrations
    remote_write:
    - basic_auth:
        password: xxx
        username: yyy
      url: https://prometheus-us-central1.grafana.net/api/prom/push
  global:
    scrape_interval: 15s
  wal_directory: /tmp/grafana-agent-wal
server:
  http_listen_port: 12345

--- Enabling and starting grafana-agent.service


Grafana Cloud Agent is now running! To check the status of your Agent, run:
   sudo systemctl status grafana-agent.service
```

These are the problematic lines in the installer:

```bash
  log '--- Retrieving config and placing in /etc/grafana-agent.yaml'
  retrieve_config | sudo tee /etc/grafana-agent.yaml
```

This should default to either keeping the existing file or prompting the user if he wants to overwrite it, like dpkg does.

**Comment by rfratto** [comment]
Hey, thanks for the input. I agree that the behavior is surprising, and we're still thinking of ways to address it. The original idea was that installing the agent would sync your config file with the integrations you've installed on the cloud, but the initial implementation is (obviously) flawed. 

I'm hesitant take away the overwriting in the short term since it's hypothetically still beneficial for users who don't need to make manual changes to their configs, and I'd prefer waiting until we have something better in place for both sides of this. 

In the meantime, the workaround would be to create your own config file at a different path and change the environment file at `/etc/default/grafana-agent` to point to the custom config instead. I'll work with the documentation team to have this listed somewhere (cc @matthewhelmke) so we make it clearer how people can escape-hatch out of the overwriting.
