### ISSUE TITLE
Flow service no longer automatically restarts in background

### ISSUE THREAD

**Issue by rfratto** [grafana/agent#5577]
PR #4824 introduced this line:

https://github.com/grafana/agent/blob/911021c6dc7dd6bfa71ae7724403d5f68980f2cb/cmd/grafana-agent-service/service.go#L79

This breaks behaviour which was by design: if the managed service exited, it would be restarted automatically with exponential backoff.

I'm opening this issue to discuss #4824 and identify why the change is needed. 

cc @jkroepke @mattdurham

**Comment by jkroepke** [comment]
> why the change is needed.

If I remember correctly, then the service errored (service exited exit code 1 was written to Event Logs) and then nothing happens anymore. I could not see any automatic restart behavior. Before #4824, Grafana Agent Flow just exit the service with exit code 0, even without an explicit os.exit call. I though, adding the exit code make sense, since the services exited anyways.

Now, we are using the Windows builtin service recovery which restarts the service only if exit code is greater than 1.

**Comment by rfratto** [comment]
Fixed by #5833.
