### ISSUE TITLE
vCenter vs vSphere metrics - documentation is confusing

### ISSUE THREAD

**Issue by wally007** [grafana/agent#6363]
### Request

Under vSphere exporter documentation it states:
`NOTE: We recommend to use [otelcol.receiver.vcenter] instead.`

When I navigate to vCenter exporter documentation it states:
`EXPERIMENTAL: This is an [experimental] component. Experimental components are subject to frequent breaking changes, and may be removed with no equivalent replacement.`

### Use case

If a new user is planning to use Grafana Agent to scrape VMware metrics, it is confusing which one to choose. 
Could you please clarify ?

**Comment by ptodev** [comment]
Hi, thank you for raising an issue - I agree that this is confusing. [prometheus.exporter.vsphere](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.exporter.vsphere/) is a component which we would like to label as deprecated soon. Some issues were reported with it, and we would like to redirect users to [otelcol.receiver.vcenter](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.receiver.vcenter/) instead. I believe there are a couple of reasons why it hasn't been made more clear in the docs:
* I'm not sure what the best way to label components or features as "deprecated" is. There is no such [stability label](https://grafana.com/docs/agent/latest/stability/) at the moment, and it's not clear whether "deprecated" should be a stability label at all or whether it should be something else.
* We need to confirm that the OTel component is at least as stable for production use as the Prometheus one. I personally don't have enough information on this, but I suspect it is the case. OTel tends to be conservative with their stability labelling, but it's usually due to potential changes in behaviour or configuration, and not because there are important bugs to be fixed.

cc @thampiotr, @clayton-cornell
