### ISSUE TITLE
Exemplars in spanmetrics?

### ISSUE THREAD

**Issue by christian-morin** [grafana/agent#697]
Enabled spanmetrics in the agent (v0.16.1)
```
spanmetrics:
  handler_endpoint: 0.0.0.0:8889
```
And I'm now scraping this endpoint as it's aggregating information. However, it's replying with the standard Prometheus-format (Content-Type: text/plain; version=0.0.4; charset=utf-8) and not the openmetrics-format. so I'm not seeing any Exemplars in the output. Sending along Header
```
-H 'Accept: application/openmetrics-text; version=1.0.0; charset=utf-8'
```
does nothing. I was hoping it would use openmetrics-format by default? Maybe I'm missing something very obvious here? Maybe it's not supposed to also present Exemplars? A shame if so though :) As it's for e.g. counting the trace errors, it would be great to be able to jump straight from an observed error to the trace from the Exemplar.

**Comment by mapno** [comment]
Hi @christian-morin! There are a couple of things here. The Grafana Agent uses OTel's [prometheus exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/prometheusexporter) to export metrics generated from spans. Sadly, the exporter does not [enable](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/prometheusexporter/prometheus.go#L71) OpenMetrics (but that is easily fixable).

I've tried enabling OpenMetrics format locally and requesting metrics and works fine. (Note that version is `0.0.1`, not `1.0.0`). The problem is that these metrics are not generating exemplars at the moment. That is something we want spend time on in the near future.

**Comment by christian-morin** [comment]
Thank you @mapno for the information! Hoping exemplars makes it into OTel's prometheus exporter soon then. Would be great! :)
