### ISSUE TITLE
Agent installation docs are confusing / bare installation feature set?

### ISSUE THREAD

**Issue by flokli** [grafana/agent#716]
Right now, https://github.com/grafana/agent/blob/main/production/kubernetes/README.md and https://github.com/grafana/agent/blob/main/production/README.md#install-script-for-kubernetes prompt users to install three different things, each coming with their own Deployments, and sometimes DaemonSets.

The grafana.com website links to the instructions at `https://$slug.grafana.com/a/grafana-easystart-app?selected=kubernetes`, which asks users to use the `install-base.sh` script.

This one only deploys a single deployment, and the RBAC stuff around it.

However, the alongside ConfigMap also contains some loki configuration. It doesn't contain Jaeger configuration.

I'm confused about the state of this, and what's right now the proper way to install grafana-agent in k8s.

**Comment by rfratto** [comment]
From the Grafana Cloud perspective, the instructions it gives you for installing on Kubernetes are the right way to go. The ConfigMap is made to work with existing integrations, which is why you don't see any tracing configs yet, but you're free to modify the manifests to suit your needs. 

We're currently planning on putting most of our Kubernetes effort into the Grafana Agent Operator and having that be the recommended strategy for installing and configuring the Grafana Agent in Kubernetes. Once we're closer to a feature-complete release of the Operator, we'll synchronize all the instructions for Grafana Cloud and non-Grafana Cloud to be as similar as possible to remove confusion, and deprecate all the existing install scripts.

**Comment by alewis001** [comment]
Sorry, I'm also very confused by what to actually do. I followed the instructions from the "Kubernetes Instructions" which installed the agent and I do get metrics in my Grafana Cloud account, which is great. However, I don't know what to do to get Loki logs as they do not appear Grafana Cloud. From what I've read it somewhat suggests that it includes logs gathering but that doesn't appear to be working. All other avenues for installing Loki that I've looked at look like they are installing Promtail standalone rather than using the Agent.

I guess my question is, does the Grafana Agent include log gathering and sending to Grafana Cloud. If it does, that at least gives me a place to start in order to try to find out why I'm not seeing logs in Grafana Cloud. Otherwise, please can you point me to the instructions I should be following to get Loki/Promtail set up on Kubernetes with Grafana Cloud?

**Comment by rfratto** [comment]
> I guess my question is, does the Grafana Agent include log gathering and sending to Grafana Cloud. If it does, that at least gives me a place to start in order to try to find out why I'm not seeing logs in Grafana Cloud. Otherwise, please can you point me to the instructions I should be following to get Loki/Promtail set up on Kubernetes with Grafana Cloud?

The Grafana Agent has the capability to gather logs, but AFAIK most of the getting started guides on Grafana Cloud don't yet include guides for how to get started with this. 

While I'm happy to help, the number of maintainers watching this repo for support questions is limited, and we try to keep this focused on Grafana Agent as an OSS project. If you need faster help with using Grafana Agent for Grafana Cloud, I'd recommend the [community forums](https://community.grafana.com/): it's monitored by much more people (including staff) and you'll likely find much faster help there.

**Comment by alewis001** [comment]
That's great, thank you @rfratto I'll try the forums.

**Comment by flokli** [comment]
> We're currently planning on putting most of our Kubernetes effort into the Grafana Agent Operator and having that be the recommended strategy for installing and configuring the Grafana Agent in Kubernetes. Once we're closer to a feature-complete release of the Operator, we'll synchronize all the instructions for Grafana Cloud and non-Grafana Cloud to be as similar as possible to remove confusion, and deprecate all the existing install scripts.

Thanks! Very much looking forward for that release to happen.

**Comment by flokli** [comment]
Let's close this issue, if most of the docs will be deprecated once that's out - or at least no more installer script, this issue won't apply.

**Comment by hjet** [comment]
Also see https://github.com/grafana/agent/pull/749#issuecomment-885926742 for more context on the recent changes
