### ISSUE TITLE
grafana-agent's k8s cluster scraping rules differ from default prometheus ones

### ISSUE THREAD

**Issue by flokli** [grafana/agent#734]
Right now, grafana-agent only scrapes application pods if they have a
port ending with -metrics:

https://github.com/grafana/agent/blob/main/production/tanka/grafana-agent/v1/lib/prometheus.libsonnet#L109-L111

This is a bit inconsistent with how it's normally done:
https://www.weave.works/docs/cloud/latest/tasks/monitor/configuration-k8s/

This is very unintuitive, as the [Quickstart introductions](https://github.com/grafana/agent/tree/main/production#install-script-for-kubernetes) don't mention that (they don't explain any differing behaviour)

**Comment by rfratto** [comment]
Hey, we mention this in the [getting started guide](https://github.com/grafana/agent/blob/main/docs/getting-started/_index.md#kubernetes-install-script) in docs but forgot to bring it over to the other document. We should probably consolidate instead of duplicate here. 

Historically, these have been taken from the [Grafana Labs Jsonnet](https://github.com/grafana/jsonnet-libs/blob/2619bb87ecb336a59616df4c1fe8ced668bdbc94/prometheus/scrape_configs.libsonnet) though I agree they're uncommon in the wild and probably unexpected for most people. 

I'm planning on moving away from those scraping rules, but it's going to be a slow migration. I think most Kubernetes users expect the Prometheus Operator CRDs nowadays, and that's where we're putting our effort into in terms of Kubernetes support. Within the coming months we'll remove all mentions of the old quickstarts and only publicly document the Grafana Agent Operator. 

(Of course, people will always be free to roll their own manual Grafana Agent Deployment and do whatever they want with kubernetes_sd_configs, but we'll likely not heavily document it, at least not at first.)
