### ISSUE TITLE
Docs feedback: /configuration/_index.md

### ISSUE THREAD

**Issue by fornellas** [grafana/agent#833]
This page references:

```
server_config
prometheus_config
loki_config
tempo_config
integrations_config
```
but examples [here](https://grafana.com/docs/grafana-cloud/quickstart/agent-k8s/k8s_agent_metrics/) refer to these keys without the `_config` suffix.

**Comment by rfratto** [comment]
Thanks for the feedback @fornellas. This is a little confusing because the `_config` suffixes refer to the schema, not the key within the config. You can see at the bottom of [/configuration/_index.md](https://github.com/grafana/agent/blob/main/docs/configuration/_index.md) that we use the `server`/`prometheus`/`loki`/etc config keys as expected.
