### ISSUE TITLE
Option to add multiple redis addresses in redis_exporter

### ISSUE THREAD

**Issue by mvkrishna86** [grafana/agent#847]
Right now, redis integration is accepting only one address. When we need to monitor multiple redis instances, we will have to install redis-exporter externally which can be eliminated if we have an option to have option to enter multiple redis addresses.

**Comment by rfratto** [comment]
Hi, thanks for opening an issue. I definitely agree this is a problem. This is an issue across most integrations, and we've been exploring the idea of allowing multiple instances of integrations (#350) to have a general solution. This would allow you to instantiate one redis exporter integration per server you want to monitor. 

We're concerned that adding support for multiple servers in individual exporters won't scale since they're upstream projects we don't maintain.

**Comment by rfratto** [comment]
Hey @mvkrishna86, I still agree that this is a problem and needs to be resolved, but we're planning on a general solution through #350 so I'm going to close this. Thanks for opening an issue!
