### ISSUE TITLE
Add loki external-labels via command line argument

### ISSUE THREAD

**Issue by james-callahan** [grafana/agent#924]
In promtail, you can use `--client.external-labels` to add external labels to your loki client config.
This is useful, particularly for e.g. hostname: e.g. passing `--client.external-labels=nodename=%H` in a systemd config.

How can I do the same thing when swapping out promtail for grafana-agent?

**Comment by rfratto** [comment]
You can't set it at the command line today, but you can set it within the YAML and use an environment variable (like `${HOSTNAME}`) that gets expanded with `--config.expand-env`. You can also modify the systemd unit to set `%H` to an environment variable. See what we've done here for an example: https://github.com/grafana/agent/blob/main/packaging/deb/grafana-agent.service

More command line options might be a good idea, but I'm not sure how they'd work, since you can have more than one logs instance defined (via `loki.configs` in the YAML). Should the command line switch affect all defined log configs? WDYT?

**Comment by james-callahan** [comment]
> More command line options might be a good idea, but I'm not sure how they'd work, since you can have more than one logs instance defined (via `loki.configs` in the YAML). Should the command line switch affect all defined log configs? WDYT?

Hmm. looks like for prometheus we have a `global` section: https://grafana.com/docs/agent/latest/configuration/prometheus-config/#global_config which includes `external_labels`.
The same thing should probably exist for loki.

**Comment by rfratto** [comment]
I've historically regretted adding the global section for prometheus since I think it's weird to affect every config, but since it exists (and probably won't go away), a global section for logs and traces sounds reasonable. 

Maybe there's a way we can define flags that only modify a specific logs config? `--logs.instance-flags=default="--client.external-labels=nodename=%H"` (this specific syntax is a bit ugly, but there might be a path here)

**Comment by james-callahan** [comment]
At least in my case for adding an external-label for hostname, I *do* want it to be added to every client.

**Comment by james-callahan** [comment]
> you can set it within the YAML and use an environment variable (like `${HOSTNAME}`) that gets expanded with `--config.expand-env`. You can also modify the systemd unit to set `%H` to an environment variable. See what we've done here for an example: https://github.com/grafana/agent/blob/main/packaging/deb/grafana-agent.service

I notice that in the service file you *don't* pass `--config.expand-env`....

**Comment by rfratto** [comment]
> I notice that in the service file you don't pass --config.expand-env....

Thanks for pointing that out, it's a pretty silly mistake. We added `--config.expand-env` recently and hadn't yet prescribed it to always be present across the various ways to deploy the agent. The general suggestion should still hold though, mix `Environment=HOSTNAME=%H` with passing `--config.expand-env` (which can is defined in the `EnvironmentFile` we provide)

> At least in my case for adding an external-label for hostname, I do want it to be added to every client.

Thanks, thanks a good point. I do agree a way to set some defaults across all configs is valuable, and I'm open to contributions for this from anyone. The one thing the implementor might need to consider is the behavior of defining both globals + locals. Gut feeling says defined locals should take precedence over globals, though I think it's still up for debate.

**Comment by james-callahan** [comment]
> The one thing the implementor might need to consider is the behavior of defining both globals + locals. Gut feeling says defined locals should take precedence over globals, though I think it's still up for debate.

globals should be a default; locals override.

**Comment by rfratto** [comment]
That’s the same thing as I said, isn’t it?

**Comment by james-callahan** [comment]
I'd still like to see this feature.

**Comment by korenlev** [comment]
or any other allowing easy agent setup of external label

**Comment by rfratto** [comment]
The current line of thinking is that flags are reserved for things that can't be reconfigured at runtime, while everything that can be reconfigured at runtime goes to the YAML. This isn't something we do today, but we're interested in moving towards that future. 

That said, it seems to me like a `global` section for logs would be the most appropriate here like James pointed out: 

> Hmm. looks like for prometheus we have a global section: https://grafana.com/docs/agent/latest/configuration/prometheus-config/#global_config which includes external_labels.
The same thing should probably exist for loki.

I'd be willing to help review a PR to add a global section for logs, but right now I'm hesitant to add any more flags until we have a clearer idea of how to separate static/dynamic settings.

**Comment by james-callahan** [comment]
This is still relevant. @rfratto can we stop stale bot from closing it?

**Comment by rfratto** [comment]
I'll re-open for discussion.

**Comment by rfratto** [comment]
Our stance on command line flags has changed since this was originally opened. The current pattern is:

* The config file is used for values which can be updated at runtime 
* Command line flags are used for values which cannot be updated at runtime 
* There is no overlap between the two 

You'll find many counterexamples where this isn't currently true; but we're working on cleaning those up. At the moment, unless we change that strategy, I'd say it's important that we don't make the current situation any worse by adding new flags which currently exist as config file options. 

Would you still be happy with a globals section for logs? That would be easier for us to include today compared to command line flags.

> This is still relevant. @rfratto can we stop stale bot from closing it?

Just a quick note on the stale bot: the stale bot closing an issue doesn't mean something isn't relevant, just that it's not receiving any attention from the maintainers or external contributors. Contributors are more than welcome to open a PR to resolve an issue or request that was previously closed as stale, but we use the stale bot to avoid having an infinitely growing backlog of issues that haven't had comments in years.

This issue isn't likely something we'll implement ourselves near term, so I'd encourage anyone reading this that is interested to contribute a PR for a globals section. I'd be more than happy to point in the right direction for how this can be implemented.
