### ISSUE TITLE
Kubernetes security: Potentially remove privileged: true from sample Loki configs

### ISSUE THREAD

**Issue by eamonryan** [grafana/agent#946]
There's a number of places where an agent deployment that configures promtail/a Loki config sets a privileged container:

https://github.com/grafana/agent/blob/22115e60df38ca482d59d25075c8533741764b95/production/tanka/grafana-agent/v2/internal/helpers/logs.libsonnet#L18

https://github.com/grafana/agent/blob/e874ac465849e33ddb77bd121ce5357bdf894b99/production/tanka/grafana-agent/grafana-agent.libsonnet#L45

https://github.com/grafana/agent/blob/20abdfc468015047e98d280b4ff248d3119efdd6/production/kubernetes/agent-loki.yaml#L74

While this is likely inherited from base promtail configs - I think it'd be good to evaluate whether it is still needed.

`hostPath` mounts can be performed without using a privileged container, so unless there is a specific other reason to run as privileged, such as needing to _*write*_ to a hostPath, I'm not sure it's necessary:

https://kubernetes.io/docs/concepts/storage/volumes/#hostpath

```
The files or directories created on the underlying hosts are only writable by root. You either need to run your process as root in a privileged Container or modify the file permissions on the host to be able to write to a hostPath volume
```

**Comment by rfratto** [comment]
We've been doing some testing, and we're pretty positive that `privileged: true` _is_ required for hostPath volume mounts. From the [Kubernetes docs](https://kubernetes.io/docs/concepts/storage/volumes/):

> The files or directories created on the underlying hosts are only writable by root. You either need to run your process as root in a [privileged Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) or modify the file permissions on the host to be able to write to a hostPath volume

So, unfortunately, I'm going to close this as won't do. Sorry!

As an alternative, the new Flow components `loki.source.kubernetes` and `loki.source.podlogs` can read logs from the Kubernetes API instead of using the host filesystem.
