### ISSUE TITLE
Container/Kubernetes security: Evaluate whether the agent container image could run as non-root

### ISSUE THREAD

**Issue by eamonryan** [grafana/agent#948]
It's documented in various places online that running containers as not-root is a security best practice e.g. https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/

Some Kubernetes distributions like OpenShift force this, in fact. 
https://engineering.bitnami.com/articles/running-non-root-containers-on-openshift.html

It would be great to evaluate the LoE involved in adjusting the Grafana Agent to run as a non-root user.

**Comment by rfratto** [comment]
We now have the knowledge to answer this: root is absolutely required for collecting logs via the filesystem of the node or running the node_exporter integration. 

If you want to disable root, you need to find alternatives to these options (i.e., using the loki.source.kubernetes/loki.source.podlogs Flow components, or collecting as much metrics as you can with via cAdvisor instead of node_exporter).

**Comment by harishkashyap569** [comment]
Is there a option to run the agent as non root for the folks who don’t need podlogs nor the node_exporter ?
