### ISSUE TITLE
Grafana Agent should expose labels from the node it's running on when host_filter is enabled

### ISSUE THREAD

**Issue by thejosephstevens** [grafana/agent#980]
Hi there!

We manage our clusters as node pools split up between interactive workloads and batch processing workloads, and as a result it's valuable for us to be able to aggregate things like resource usage grouped by node pool so we can understand things like resource contention at the level of a node pool.

Today it's possible to embed labels from a node if you are scraping a target discovered through node service discovery (with `__meta_kubernetes_node_label_<labelname>`, but node labels aren't available to you if you discover a workload through another SD method (in the case of an agent daemonset this would most commonly be pod).

It would be great if the grafana agent could expose node labels when running in `host_filter` mode, either through something like `__meta_kubernetes_node_label_<labelname>`, or even through a special set of environment variables like `META_NODE_LABEL_<LABELNAME>`.

Thanks!

**Comment by rfratto** [comment]
Thank you! This is an interesting proposal: many people run the agent per-machine, and that use case probably won't go away, especially since it needs to be deployed like that to collect logs. That said, I think we need to spend some time thinking about what options are available here: 

The naive approach would probably be to find a way to reuse Prometheus SD to expose environment metadata to the agent. This probably wouldn't work very well though; SD is designed to stream updates and we would need some kind of hack to identify a machine's metadata, so I'm generally a little uncomfortable with trying to find a way to make this work. 

It sounds like we would need some generic system that can discover environment metadata at start time. Something similar to [hashicorp/go-discover](https://pkg.go.dev/github.com/hashicorp/go-discover) might be appropriate here. 

Unless we find another way to do this, it sounds like this might be a fair amount of work to build and maintain. I'd love alternative ideas of how we can approach this (or if we should be implementing it at all, I guess).
